Remove ConfigService.ts, Enahance Certifcate Stage
zowe/zen pull request #114
Opened 2024-01-30 06:41 UTC by timgerstel

## Proposed changes
This PR combines these two PRs:
- https://github.com/zowe/zen/pull/79
- https://github.com/zowe/zen/pull/79

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Change in a documentation
- [ ] Refactor the code 
- [ ] Chore, repository cleanup, updates the dependencies.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## PR Checklist
Please delete options that are not relevant.
- [ ] If the changes in this PR are meant for the next release / mainline, this PR targets a "staging" branch.
- [ ] My code follows the style guidelines of this project (see: [Contributing guideline](https://github.com/zowe/zen/blob/v2.x/staging/CONTRIBUTING.md))
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes
- [ ] video or image is included if visual changes are made

- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works, or describe a test method below

## Testing

## Further comments

2024-02-12 14:27 UTC, DivergentEuropeans commented on src/renderer/preload.ts
> +    installButtonOnClick(connectionArgs: IIpcConnectionArgs, installationArgs: {installDir: string, javaHome: string, nodeHome: string, installationType: string, userUploadedPaxPath: string, smpeDir:
what is this skipDownload stuff for? If it's for smpe, why don't we just check if smpeDir exists? Wasn't that the reason why we made that variable in the first place instead of setting installationDir = smpeDir and deleting smpeDir entirely

Also, it looks like it's never actually set any where, except 1 default
`window.electron.ipcRenderer.installButtonOnClick(connectionArgs, installationArgs, version, yaml, skipDownload ?? false)`

2024-02-12 15:05 UTC, timgerstel commented on src/renderer/preload.ts
> +    installButtonOnClick(connectionArgs: IIpcConnectionArgs, installationArgs: {installDir: string, javaHome: string, nodeHome: string, installationType: string, userUploadedPaxPath: string, smpeDir:
It was for QA testing, not a prod solution. It was so @struga0258 can skip the pax download process.

2024-02-12 15:08 UTC, timgerstel commented on src/renderer/preload.ts
> +    installButtonOnClick(connectionArgs: IIpcConnectionArgs, installationArgs: {installDir: string, javaHome: string, nodeHome: string, installationType: string, userUploadedPaxPath: string, smpeDir:
And its set here: https://github.com/zowe/zen/pull/114/files#diff-876487e16434db86af62a71372589b9b6ee12ec10cc731bc989c96eb78d3b17fR196

2024-02-12 21:52 UTC, DivergentEuropeans commented on src/renderer/preload.ts
> +    installButtonOnClick(connectionArgs: IIpcConnectionArgs, installationArgs: {installDir: string, javaHome: string, nodeHome: string, installationType: string, userUploadedPaxPath: string, smpeDir:
Oh I see. Yes, we need a better solution for the smpe step

2024-02-23 16:20 UTC, DivergentEuropeans requested changes
we need a better solution for the smpe step/QA testing hack

2024-03-06 16:53 UTC, DivergentEuropeans requested changes

2024-03-06 16:53 UTC, DivergentEuropeans commented on src/actions/InstallActions.ts
> +      return new FTPInstallation().initCertificates(connectionArgs, installationArgs.installationDir, zoweConfig)
This doesn't seem right. It seems like 
1. initCertificates( ) should should belong in `Installation `class, with initSecurity, +
initCertificates should be made public
2. change this to
`return this.strategy.initCertificates(connectionArgs, installationArgs.installationDir, zoweConfig);`

2024-03-06 16:53 UTC, DivergentEuropeans commented on src/actions/InstallationHandler.ts
> +        download = upload = unpax = {status: true, details : ''}
Never seen that b4 for some reason, cool 👍

2024-03-06 16:53 UTC, DivergentEuropeans commented on src/actions/InstallationHandler.ts
> +    const script = `cd ${installDir}/runtime/bin;\n./zwe init certificate --update-config -c ${installDir}/zowe.yaml`;
you no longer need "\n" as it's handled automatically however we do want to make sure we're using "&&" instead of ";"

2024-03-06 16:53 UTC, DivergentEuropeans commented on src/main/index.ts
> +  ipcMain.handle('zwe-init-certificates', async (event, connectionArgs, installationArgs, zoweConfig) => {
why does this have `zwe-init-certificates` but below is `init-apf `?

2024-03-06 16:53 UTC, DivergentEuropeans commented on src/actions/InstallActions.ts
> +      return new FTPInstallation().initCertificates(connectionArgs, installationArgs.installationDir, zoweConfig)
Also, the commands below don't include the `Zwe `part so I guess we could remove that for organization's sake

2024-03-08 00:37 UTC, DivergentEuropeans approved these changes
Changes addressed

2024-03-08 00:41 UTC, merged