Feature/resume stage
zowe/zen pull request #116
Opened 2024-02-06 13:19 UTC by sakshibobade21

## Proposed changes

This PR addresses Issue: [*Link to Github issue within https://github.com/zowe/zen/issues* if any]

This PR depends upon the following PRs:

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Change in a documentation
- [ ] Refactor the code 
- [ ] Chore, repository cleanup, updates the dependencies.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## PR Checklist
Please delete options that are not relevant.
- [ ] If the changes in this PR are meant for the next release / mainline, this PR targets a "staging" branch.
- [ ] My code follows the style guidelines of this project (see: [Contributing guideline](https://github.com/zowe/zen/blob/v2.x/staging/CONTRIBUTING.md))
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes
- [ ] video or image is included if visual changes are made

- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works, or describe a test method below

## Testing

## Further comments

2024-02-12 21:19 UTC, DivergentEuropeans requested changes
Great feature @sakshibobade21 another absolute banger from you 👍 I spotted a couple small things though

![image](https://github.com/zowe/zen/assets/20528015/033022ce-3924-41d2-9615-2f0a3a2869b0)

1. UI is off-centered slightly, missing shadow like the other tiles

2. run-time error resuming from getting past Connection, into Planning step. Leaving Planning and resuming Planning then clicking Validate Locations. I see a couple options:

a) is safety isn't compromised, store password in state. I think this is a no-go because of our message "Your password is securely stored for only the current session." prove me wrong if you think of something @sakshibobade21 

b) make manual exception for: if user resumed at Step 2, go back to Step 1 AND make UX pop-up appear that password needs to be retyped. Make sure previously typed in stuff in Step 2 appears when we resume + go from Step 1 --> Step 2

2024-02-13 12:36 UTC, sakshibobade21 commented
> Great feature @sakshibobade21 another absolute banger from you 👍 I spotted a couple small things though
> 
> ![image](https://private-user-images.githubusercontent.com/20528015/304222673-033022ce-3924-41d2-9615-2f0a3a2869b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MjgwNzksIm5iZiI6MTcwNzgyNzc3OSwicGF0aCI6Ii8yMDUyODAxNS8zMDQyMjI2NzMtMDMzMDIyY2UtMzkyNC00MWQyLTk2MTUtMmYwYTNhMjg2OWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDEyMzYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViNzlkMWI3MDk1YThiOGJhYjkxMjUxNzdhZmFiNmFmZGZmNDc1YjdlNzA1ZmE2ZTMxMzY3ZDQ2ZWNjYzMyMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RbaFbh4tAj5j54u9j69X66LvfbR_yGNgYdpcQ9FmegU)
> 
> 1. UI is off-centered slightly, missing shadow like the other tiles
> 2. run-time error resuming from getting past Connection, into Planning step. Leaving Planning and resuming Planning then clicking Validate Locations.
> 
> `(node:13668) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'close') at C:\Users\lastrakou\Desktop\zlux5\zen\.webpack\main\index.js:24935:28 at Generator.throw (<anonymous>) at rejected (C:\Users\lastrakou\Desktop\zlux5\zen\.webpack\main\index.js:24909:65) at process.processTicksAndRejections (node:internal/process/task_queues:96:5) (node:13668) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict`(see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5) Error occurred in handler for 'check-dir-or-create': Error: password missing from PASS command at makeError (C:\Users\lastrakou\Desktop\zlux5\zen\.webpack\main\index.js:9059:13) at Parser.<anonymous> (C:\Users\lastrakou\Desktop\zlux5\zen\.webpack\main\index.js:8076:25) at Parser.emit (node:events:513:28) at Parser._write (C:\Users\lastrakou\Desktop\zlux5\zen\.webpack\main\index.js:9131:10) at writeOrBuffer (node:internal/streams/writable:391:12) at _write (node:internal/streams/writable:332:10) at Writable.write (node:internal/streams/writable:336:10) at TLSSocket.ondata (C:\Users\lastrakou\Desktop\zlux5\zen\.webpack\main\index.js:8237:20) at TLSSocket.emit (node:events:513:28) at addChunk (node:internal/streams/readable:315:12) { code: 501 } Error occurred in handler for 'check-dir-or-create': Error: password missing from PASS command at makeError (C:\Users\lastrakou\Desktop\zlux5\zen\.webpack\main\index.js:9059:13) at Parser.<anonymous> (C:\Users\lastrakou\Desktop\zlux5\zen\.webpack\main\index.js:8076:25) at Parser.emit (node:events:513:28) at Parser._write (C:\Users\lastrakou\Desktop\zlux5\zen\.webpack\main\index.js:9131:10) at writeOrBuffer (node:internal/streams/writable:391:12) at _write (node:internal/streams/writable:332:10) at Writable.write (node:internal/streams/writable:336:10) at TLSSocket.ondata (C:\Users\lastrakou\Desktop\zlux5\zen\.webpack\main\index.js:8237:20) at TLSSocket.emit (node:events:513:28) at addChunk (node:internal/streams/readable:315:12) { code: 501 }`
> 
> I see a couple options:
> 
> a) if safety isn't compromised, store password in state. I think this is a no-go because of our message "Your password is securely stored for only the current session." prove me wrong if you think of something @sakshibobade21
> 
> b) make manual exception for: if user resumed at Step 2, go back to Step 1 AND make UX pop-up appear that password needs to be retyped. Make sure previously typed in stuff in Step 2 appears when we resume + go from Step 1 --> Step 2

Thank you Lenny. I addressed the changes you requested.

2024-02-13 12:37 UTC, sakshibobade21 commented
Thank you @DivergentEuropeans I addressed the changes you requested.

2024-02-14 18:16 UTC, timgerstel requested changes
Just did a quick look, will do a more in-depth review later. Saw a lot of hard coded consts that should have been read from Wizard.tsx. Will test this PR this evening as well.

2024-02-14 18:16 UTC, timgerstel commented on src/renderer/components/stages/Certificates.tsx
> +  const STAGE_ID = 3;
These variables should be read from Wizard.tsx, not hard coded

2024-02-14 18:16 UTC, timgerstel commented on src/renderer/components/stages/InitApfAuth.tsx
> +  const STAGE_ID = 3;
Set variables from stages export in Wizard.tsx

2024-02-14 23:23 UTC, timgerstel submitted a review, later dismissed

2024-02-14 23:23 UTC, timgerstel commented on src/renderer/components/stages/Planning.tsx
> +                value={installationArgs.installationDir || localYaml?.zowe?.runtimeDirectory}
Why is the order of all the OR statements in this block being switched?

2024-02-14 23:23 UTC, timgerstel commented on src/renderer/components/Home.tsx
> +          password: connectionPassword,
Is this password really securely stored? I know this is unrelated to your PR but it should be checked

2024-02-16 06:49 UTC, sakshibobade21 commented on src/renderer/components/stages/Certificates.tsx
> +  const STAGE_ID = 3;
Hi Tim,
I agree with you. But to read from Wizard we need some starting point(Either stage id, or stage label etc).
So, I am now removing the hardcoded stage ids and fetching it from wizard using the stage label.

`export const getStageDetails = (stageLabel: string) => {
  const stage = stages.find(stage => stage.label === stageLabel);
  return stage;
}`

2024-02-16 07:37 UTC, sakshibobade21 commented on src/renderer/components/stages/Planning.tsx
> +                value={installationArgs.installationDir || localYaml?.zowe?.runtimeDirectory}
There is an issue in the planning stage. The very last thing updated in the form in planning stage is not retained
To reproduce
1) Change something in planning form, say runtime directory
2) Change some other field, say log directory.
3) Go back to the Connection Stage
4) Navigate to the planning stage again.

You will notice that the changes in the runtime directory is present in the form but not for the log directory.
I believe this is because of the asynchronous calls inside the useEffect hook in the planning stage.

On the other hand "installationArgs" has the latest updated values for all the fields. So referring to the installationArgs at the first place ensures consistency in the form

Let me know if that makes sense to you,

2024-02-16 07:38 UTC, sakshibobade21 commented on src/renderer/components/Home.tsx
> +          password: connectionPassword,
We need the password in the multiple stages in ZEN. So we need to store it.
To make it more secure we can plan to implement jwt auth or any other auth mechanism.

2024-02-16 14:45 UTC, skurnevich commented
Here are some UI examples that we had, just for an inspiration:

<img width="1029" alt="Screenshot 2024-02-16 at 15 22 58" src="https://github.com/zowe/zen/assets/61471197/1819310c-2aa2-48af-ac2e-d496a118bedd">
<img width="777" alt="Screenshot 2024-02-16 at 15 26 27" src="https://github.com/zowe/zen/assets/61471197/a6e00e80-9687-4d0f-a95f-969d0e89e757">

2024-02-19 06:00 UTC, sakshibobade21 commented
@skurnevich The UI ideas look great. It will be useful for the upcoming enhancements.

2024-02-20 15:03 UTC, DivergentEuropeans approved these changes

2024-02-20 15:04 UTC, DivergentEuropeans commented
@sakshibobade21 can you make a ticket for @timgerstel 's point about password storage?

2024-02-20 15:07 UTC, merged