[WIP] State Management
zowe/zen pull request #132
Opened 2024-03-11 13:17 UTC by sakshibobade21

## Proposed changes

This PR addresses Issue: [*Link to Github issue within https://github.com/zowe/zen/issues* if any]

This PR depends upon the following PRs:

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Change in a documentation
- [ ] Refactor the code 
- [ ] Chore, repository cleanup, updates the dependencies.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## PR Checklist
Please delete options that are not relevant.
- [ ] If the changes in this PR are meant for the next release / mainline, this PR targets a "staging" branch.
- [ ] My code follows the style guidelines of this project (see: [Contributing guideline](https://github.com/zowe/zen/blob/v2.x/staging/CONTRIBUTING.md))
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes
- [ ] video or image is included if visual changes are made

- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works, or describe a test method below

## Testing

## Further comments

2024-04-11 22:41 UTC, timgerstel commented
Bugs
1) This PR is causing each stage to automatically scroll all the way to the bottom. Changing stage/clicking next or previous should bring you to the top of the new stage.

2) The "Save & Close" + Resume feature are also not persisted in this PR. When you click "Save & Close", you are shown a box on the home page that says "Resume progress: <date>" but if you restart the app it never reappears.

3) Java version and node version do not reappear on planning stage 
![image](https://github.com/zowe/zen/assets/7998484/247aec5e-91cb-4e41-9fb6-4706f29c8bce)

4) Status of stages are not being saved (all stages) or shown in the stepper.

5) After restarting the app, installation progress automatically appears after license agreement when installation was skipped on previous run:
![image](https://github.com/zowe/zen/assets/7998484/cfcf3309-20ab-441f-9529-d6aaf31cd352)

6) "Continue" button should be enabled on "Installation stage" instead of skip but is perhaps related to bug 5 (maybe does not think the installation was successful)

7) Security stage shows green check when it has not been run, automatically shows progress status when "zwe init security" has not been run:
![image](https://github.com/zowe/zen/assets/7998484/429f7387-bf99-4468-b568-40dca458b9d4)

8) Certificate stage shows green checkmark without running "zwe init certificates"

9) Certificate stage automatically scrolls to bottom by default after restarting app but not running zwe init actions

10) Entering values into fields when progress bars are shown causes page to automatically scroll to bottom



This PR definitely needs some reworking @sakshibobade21

2024-04-11 22:54 UTC, timgerstel commented on src/renderer/components/stages/Planning.tsx
> +  const setPlanningState = (status: boolean): void => {
These setters should either be wrapped in a useState() or moved elsewhere, having class variables defined that arent useState/useMemo/useRef etc are expensive on memory in React if I recall correctly

2024-04-11 23:00 UTC, timgerstel requested changes

2024-04-11 23:00 UTC, timgerstel commented on src/renderer/components/stages/Security.tsx
> +  const setupSchema = schema?.properties?.zowe?.properties?.setup?.properties?.dataset;
This should be security not dataset

2024-04-11 23:00 UTC, timgerstel commented on src/renderer/components/stages/Security.tsx
> +  const [setupYaml, setSetupYaml] = useState(yaml?.zowe?.setup?.dataset);
security not dataset

2024-04-11 23:00 UTC, timgerstel commented on src/renderer/components/stages/Security.tsx
> +    datasetSchema = schema.properties.zowe.properties.setup.properties.dataset;
security not dataset

2024-04-11 23:00 UTC, timgerstel commented on src/renderer/components/stages/Security.tsx
> +    let updatedData = init ? (Object.keys(yaml?.zowe.setup.dataset).length > 0 ? yaml?.zowe.setup.dataset : data) : (data ? data : yaml?.zowe.setup.datasetg);
all setup.dataset should be setup.security

2024-04-11 23:00 UTC, timgerstel commented on src/renderer/components/stages/Security.tsx
> +  const yaml = useAppSelector(selectYaml);
Leave these wrapped in use state and wrap the other declarations as well

2024-04-11 23:00 UTC, timgerstel commented on src/renderer/components/stages/installation/InstallTypeSelection.tsx
> +  const validateSmpePath = async(e: any, connectionArgs: any, smpePath: string) => {
We are no longer using "smpePath", all references to this should be removed

2024-04-12 05:50 UTC, sakshibobade21 commented on src/renderer/components/stages/Planning.tsx
> +  const setPlanningState = (status: boolean): void => {
Cannot move these setters outside the component function, because they are using the component variables.
Cannot wrap it inside the useState hook because setters are not updating any state based on component variables.
These setters are just created to reuse the code.

2024-04-12 05:53 UTC, sakshibobade21 commented on src/renderer/components/stages/Planning.tsx
> +  const setPlanningState = (status: boolean): void => {
One thing that can be done is:


```
let setPlanningState: (status: boolean) => void;

  useEffect(() => {
    setPlanningState = (status: boolean): void => {
      dispatch(setNextStepEnabled(status));
      dispatch(setPlanningStatus(status));
    }
  }, [])
```
  
 But again its same as before, we still have a component variable.

2024-04-12 06:05 UTC, sakshibobade21 commented on src/renderer/components/stages/Security.tsx
> +  const setupSchema = schema?.properties?.zowe?.properties?.setup?.properties?.dataset;
Done. Thank you for spotting it.

2024-04-12 06:05 UTC, sakshibobade21 commented on src/renderer/components/stages/Security.tsx
> +  const [setupYaml, setSetupYaml] = useState(yaml?.zowe?.setup?.dataset);
Done. Thanks

2024-04-12 06:06 UTC, sakshibobade21 commented on src/renderer/components/stages/Security.tsx
> +    datasetSchema = schema.properties.zowe.properties.setup.properties.dataset;
Done. Thanks

2024-04-12 06:06 UTC, sakshibobade21 commented on src/renderer/components/stages/Security.tsx
> +    let updatedData = init ? (Object.keys(yaml?.zowe.setup.dataset).length > 0 ? yaml?.zowe.setup.dataset : data) : (data ? data : yaml?.zowe.setup.datasetg);
Done. Thanks

2024-04-12 06:24 UTC, sakshibobade21 commented on src/renderer/components/stages/Security.tsx
> +  const yaml = useAppSelector(selectYaml);
Done.

2024-04-12 06:43 UTC, sakshibobade21 commented on src/renderer/components/stages/installation/InstallTypeSelection.tsx
> +  const validateSmpePath = async(e: any, connectionArgs: any, smpePath: string) => {
We have smpe install path in staging - https://github.com/zowe/zen/blob/v2.x/staging/src/renderer/components/stages/installation/InstallTypeSelection.tsx#L121

2024-04-12 12:54 UTC, sakshibobade21 commented
@timgerstel Thank you so much for thoroughly reviewing and testing my PR.
I addressed all the bugs/issues you found.

'Automatic scroll to bottom' issue is fixed. 
Java and Node version now appears on the planning stage. 
Security and Certificate stage is not checked(green check mark) by default at startup. 
Status of all the stages is shown in the stepper, except the networking and the launch config stage. since there is not call to action. We can address this in a seperate PR.
When installation was skipped on previous run after license agreement, installation progress does nor automatically appears any more after restarting the app.
Entering values into fields when progress bars are shown does not causes page to automatically scroll to bottom any more.

2024-04-18 00:07 UTC, timgerstel commented
Bugs with this PR:

1. No actions automatically scroll to the bottom now, for example when you run any "zwe init" actions now none of them scroll to the progress cards
2. Progress cards not updating properly for zwe init actions. Tested case: run zwe init apf auth, note success in terminal output: '>> Zowe load libraries are APF authorized successfully.\r\n' +
      'Script finished.\r\n' +
      "+ echo 'Script finished.'\r\n" +
      ' !! END OF JES SPOOL FILE !!\r\n'

2024-04-18 00:12 UTC, timgerstel commented
I think those are the only 3 bugs left i could find, this PR is almost ready to merge!

2024-04-18 13:37 UTC, timgerstel commented
"Save & Close" still not working between restarts

2024-04-18 13:44 UTC, sakshibobade21 commented
@timgerstel Thanks again for retesting the PR.
I addressed the changes 1 and 2 you mentioned in the above comments.

For save and close we have a separate ticket in JIra.
Also, can we please have a separate ticket, PR for the point 3 you mentioned? I will work on it seperately
This PR has already become very bulky. 

In this PR the icons are updated after we visit the step.

2024-04-22 13:35 UTC, timgerstel commented
I know you already made a fix for one part of this bug but you broke the other scenario for scrolling, where if the user had already filled out values the completed stage (planning, anything with progress cards) does not automatically scroll to the bottom now.

![image](https://github.com/zowe/zen/assets/7998484/61109217-27a9-459a-94fe-56ca110962b6)

Clicking "zwe init" buttons for init mvs, init security etc no longer scroll the progress cards into view automatically as well.

2024-04-26 01:18 UTC, timgerstel commented
Two bugs:
1) The default/example job statement for the planning stage doesn't load on the first run
2) Styling for APF Auth page is broken, this definitely needs a little spacing which i believe it had before: 
![image](https://github.com/zowe/zen/assets/7998484/fcf65c8a-3a29-4436-af56-521a7f5503a5)

Otherwise I think this PR is ready to merge! Nice job @sakshibobade21

2024-04-29 14:02 UTC, timgerstel approved these changes

2024-05-02 13:04 UTC, merged