State Management for the Active Stage
zowe/zen pull request #155
Opened 2024-05-08 13:59 UTC by sakshibobade21

## Proposed changes

This PR manages the state for the active stage in multiple sessions

This PR depends upon the following PRs:

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Change in a documentation
- [ ] Refactor the code 
- [ ] Chore, repository cleanup, updates the dependencies.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## PR Checklist
Please delete options that are not relevant.
- [ ] If the changes in this PR are meant for the next release / mainline, this PR targets a "staging" branch.
- [ ] My code follows the style guidelines of this project (see: [Contributing guideline](https://github.com/zowe/zen/blob/v2.x/staging/CONTRIBUTING.md))
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes
- [ ] video or image is included if visual changes are made

- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works, or describe a test method below

## Testing

## Further comments

2024-05-08 14:33 UTC, timgerstel requested changes
![image](https://github.com/zowe/zen/assets/7998484/3e9990e1-4fd8-4b99-9034-653b20cb3e30)
Original resume button should be used instead, and should persist between app restarts

2024-05-08 14:59 UTC, timgerstel commented on src/renderer/components/configuration-wizard/Wizard.tsx
> +  {id: 2, label: 'Installation Type', component: <InstallationType/>, hasJCL: false, isSkippable: false, isSkipped: false, hasOutput: false, steps: 1, nextButton: 'Continue to Components Installation
Remove statusKey and use the label instead for the getProgress() arg, the objects in this array are already quite messy

2024-05-08 14:59 UTC, timgerstel commented on src/renderer/components/stages/connection/Connection.tsx
> +        window.electron.ipcRenderer.setConfig(EXAMPLE_YAML).then((res: IResponse) => {
Settings config and schema here will conflict with this PR:

https://github.com/zowe/zen/pull/146

These ipcRenderer calls as well as constants.ts should be removed.

Was there a specific reason you needed to set these here?

2024-05-08 14:59 UTC, timgerstel commented on src/renderer/components/common/Stepper.tsx
> +    if (!error || (isSubStep && getProgress(stages[stageId].subStages[subStepId].statusKey)) || (!isSubStep && getProgress(stages[stageId].statusKey))) {
Remove statusKey, use label

2024-05-08 16:11 UTC, sakshibobade21 commented
The functionality of the resume button operates as intended under two different scenarios:
When the user seeks to resume progress within the same session.
When the user intends to resume progress in a subsequent session, such as after restarting the application.
In the second scenario, adding the resume button on the home screen would be impractical, as resuming progress should only be permissible after establishing a successful connection.
Therefore, in this case, the resume button is appropriately placed within the connection stage and becomes visible only upon successful connection.
Conversely, in the first scenario where a successful connection is already established, the resume button is on the home screen, because on clicking "Save and close" you are redirected to the home screen.
Lmk if it looks good to you all. I am open for suggestions.

2024-05-08 16:15 UTC, sakshibobade21 commented on src/renderer/components/stages/connection/Connection.tsx
> +        window.electron.ipcRenderer.setConfig(EXAMPLE_YAML).then((res: IResponse) => {
This code is used to set the schema and the yaml. We need this because, when we resume to any stage say "Certificate" directly after connection we need to have the schema.

2024-05-08 16:32 UTC, sakshibobade21 commented on src/renderer/components/configuration-wizard/Wizard.tsx
> +  {id: 2, label: 'Installation Type', component: <InstallationType/>, hasJCL: false, isSkippable: false, isSkipped: false, hasOutput: false, steps: 1, nextButton: 'Continue to Components Installation
The function getProgress() retrieves an object from local storage. Keys in the local storage are stored using camel case conventions. The labels are displayed in the UI therefore they cannot be in camel case.
I prefer to maintain camel case conventions for the keys.

2024-05-12 21:37 UTC, timgerstel commented
Two very very small things:

1) On the very first run of Zen, the "Saved Installation" tile should probably be hidden since there can't be a previous installation: ![image](https://github.com/zowe/zen/assets/7998484/f951e783-ca0e-4086-8b85-643c368457fe).

2) The wording of "Validate Credentials & Continue to the Last Active Stage." is a little awkward, perhaps we should reuse "Validate Credentials & Resume" as the tooltip for the home stage resume button.

Other than that I tested this PR and it works as expected. If QA has also tested this feature, then this PR looks good to me!

2024-05-17 10:48 UTC, timgerstel approved these changes

2024-05-20 01:32 UTC, merged