Stage Persistence for Networking and Launch Config Stage
zowe/zen pull request #172
Opened 2024-06-07 13:28 UTC by sakshibobade21

## Proposed changes

This PR addresses Issue: Persist the state for the Networking and the Launch Config Stage

This PR depends upon the following PRs:

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Change in a documentation
- [ ] Refactor the code 
- [ ] Chore, repository cleanup, updates the dependencies.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## PR Checklist
Please delete options that are not relevant.
- [ ] If the changes in this PR are meant for the next release / mainline, this PR targets a "staging" branch.
- [ ] My code follows the style guidelines of this project (see: [Contributing guideline](https://github.com/zowe/zen/blob/v2.x/staging/CONTRIBUTING.md))
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes
- [ ] video or image is included if visual changes are made

- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works, or describe a test method below

## Testing

## Further comments

2024-06-10 21:24 UTC, timgerstel approved these changes

2024-06-10 21:24 UTC, timgerstel commented on src/renderer/components/common/MonacoEditor.tsx
> +import { diff } from 'deep-diff';
This library is unmaintained so it should definitely not be added. I think there's probably a better solution to the undefined "externalDomains" issue. For now if you could please remove the fix for externalDomains, I'll work on that and then I think the rest of this PR is ok so I will approve

2024-06-10 21:26 UTC, timgerstel commented on src/renderer/components/common/MonacoEditor.tsx
> +import { diff } from 'deep-diff';
We also didn't need to check the diff of the yaml on any other stages so unless there's an exception on this stage that I missed I don't think we'll need to even do a diff comparison

2024-06-10 21:27 UTC, timgerstel requested changes
Meant to request changes, approved by accident

2024-06-10 22:21 UTC, timgerstel commented on src/renderer/components/common/MonacoEditor.tsx
> +import { diff } from 'deep-diff';
Fix here: https://github.com/zowe/zen/pull/175

2024-06-11 04:12 UTC, sakshibobade21 commented on src/renderer/components/common/MonacoEditor.tsx
> +import { diff } from 'deep-diff';
I am checking the diff because if in the yaml attributes from the networking stage is updated then we should mark the networking stage as completed as discussed with @DivergentEuropeans

2024-06-11 04:13 UTC, sakshibobade21 commented on src/renderer/components/common/MonacoEditor.tsx
> +import { diff } from 'deep-diff';
If we update anything in the form then the networking stage is mark as completed.
But what if the form is not updated, but instead the networking attributes in the yaml is updated?
In this case we need to check the diff of the yaml.

2024-06-11 13:19 UTC, timgerstel commented on src/renderer/components/common/MonacoEditor.tsx
> +import { diff } from 'deep-diff';
There are much easier ways to check if the yaml has been changed or updating than by taking the diff. Diffs can be an expensive operation depending on what is being compared. Also as I stated before, the deep-diff library you added hasn't been maintained or updated in 6 years.

In my PR that fixes the networking stage, I set the stage to complete if the users yaml successfully uploads after clicking "save YAML to z/OS button" on the Networking and Launch Config stages: https://github.com/zowe/zen/pull/175/files#diff-9b9ad16497a71852bcfc086ef0d71306ec3d8ad6760ee1a2d731fc60c8ea1ee9R530


I will ask again that you please remove deep-diff and anything related. Thank you.

2024-06-11 13:24 UTC, sakshibobade21 commented on src/renderer/components/common/MonacoEditor.tsx
> +import { diff } from 'deep-diff';
We can definitely check if the yaml has been updated or not easily.
But I specifically wanted to check if the components or the launch config objects has been updated.

2024-06-11 13:25 UTC, sakshibobade21 commented on src/renderer/components/common/MonacoEditor.tsx
> +import { diff } from 'deep-diff';
I can remove the deep-diff and the associated changes but then will we need a separate ticket to change the networking and launch config stage status to completed if the yaml is upadting the config rekated to these srage?

2024-06-11 13:31 UTC, timgerstel commented on src/renderer/components/common/MonacoEditor.tsx
> +import { diff } from 'deep-diff';
I did that in my PR if you re-read my last reply

2024-06-11 13:39 UTC, sakshibobade21 commented on src/renderer/components/common/MonacoEditor.tsx
> +import { diff } from 'deep-diff';
I of course read your reply. 

I am saying this because what we are discussing now contradicts what we discussed in the grooming.

You say that you update the stage status to completion when the user's yaml successfully uploads after clicking "save YAML to z/OS button". That makes sense to me.

But what if user is on installation stage and updates the component section in the yaml? Will the networking stage still show the completion mark? According to the discussion and I believe, it should. 

Right @DivergentEuropeans ?

2024-06-11 13:45 UTC, timgerstel commented on src/renderer/components/common/MonacoEditor.tsx
> +import { diff } from 'deep-diff';
I must have missed that during grooming because I would have disagreed with that.

I do not think changing the YAML should be setting the stage status of ANY stage.

2024-06-11 13:51 UTC, sakshibobade21 commented on src/renderer/components/common/MonacoEditor.tsx
> +import { diff } from 'deep-diff';
I precisely remember that being discussed without anybody disagreeing.

2024-06-11 13:53 UTC, timgerstel commented on src/renderer/components/common/MonacoEditor.tsx
> +import { diff } from 'deep-diff';
I'm sure you're correct and I probably missed it, that's on me

2024-06-11 13:54 UTC, sakshibobade21 commented on src/renderer/components/common/MonacoEditor.tsx
> +import { diff } from 'deep-diff';
This was discussed for networking and the launch config stage.

2024-06-11 13:57 UTC, timgerstel commented on src/renderer/components/common/Stepper.tsx
> +        if(getProgress(stages[activeStep].statusKey)) {
Looks like this might make the "Unpax" stage unskippable. We want users to be able to skip the download step if they have already performed that process, even if Zen doesn't recognize/remember the status of the Unpax stage

2024-06-11 14:01 UTC, sakshibobade21 commented on src/renderer/components/common/MonacoEditor.tsx
> +import { diff } from 'deep-diff';
We can definitely update the stage to completion only when the user clicks "SAVE YAML TO ZOS".
I am just saying, I implemented what we discussed in the grooming.

2024-06-11 14:05 UTC, sakshibobade21 commented on src/renderer/components/common/Stepper.tsx
> +        if(getProgress(stages[activeStep].statusKey)) {
If you test the PR unpax stage can be skipped

2024-06-11 15:56 UTC, sakshibobade21 commented
Closing this Pull Request. Created a new one.

2024-06-14 03:50 UTC, DivergentEuropeans commented on src/renderer/components/common/MonacoEditor.tsx
> +import { diff } from 'deep-diff';
Oops, arriving to this conversation late @sakshibobade21 and @timgerstel - I was on PTO

So, because there was no button in the Networking stage, the only way to see if this stage was edited OR "skipped" is to see if any user input at all has happened. That was the previous story, discussed during a team meet so that's correct. That could be checked via diff but it seems @timgerstel gave some good reasons for not having this library. Also, like @timgerstel said, since we now have a button, let's instead link status to this button instead. Technically you never needed to do a diff in the first place @sakshibobade21 you could have just kept a listener on if any of the UI elements have been changed. Doing diff logic would be hard, because like what if you do bulk copy-pastes and stuff like that, or change Networking section while not being in Networking stage, then you need any kind of diff checking to be global - it would just get heavy quickly

2024-06-14 19:31 UTC, closed without merging