Major Refactor
zowe/zen pull request #180
Opened 2024-06-12 23:20 UTC by timgerstel

we da best

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Change in a documentation
- [ ] Refactor the code 
- [ ] Chore, repository cleanup, updates the dependencies.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## PR Checklist
Please delete options that are not relevant.
- [ ] If the changes in this PR are meant for the next release / mainline, this PR targets a "staging" branch.
- [ ] My code follows the style guidelines of this project (see: [Contributing guideline](https://github.com/zowe/zen/blob/v2.x/staging/CONTRIBUTING.md))
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes
- [ ] video or image is included if visual changes are made

- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works, or describe a test method below

## Testing

## Further comments

2024-06-13 12:50 UTC, skurnevich commented
Does not work for me:

Local pax file uploading fails
<img width="1348" alt="Screenshot 2024-06-13 at 14 34 53" src="https://github.com/zowe/zen/assets/61471197/f92cab31-8450-4206-8778-3af350005e11">

Downloading fails on schema parsing
```
14:43:42.429 › error setting schema from pax: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
```

For the last one i have created the [PR 179](https://github.com/zowe/zen/pull/179) to replace cat command output parsing with files downloading. 
You can merge it first, or incorporate changes into this PR. The factual change is smaller than it looks, you just need to replace readExampleYamlAndSchema function and remove parseExampleYamlFromPax blocks as downloaded yaml and json files are ready to use

2024-06-13 12:53 UTC, skurnevich commented on src/actions/InstallationHandler.ts
> +              yamlObj = yamlObj = Object.assign({}, yamlObj, currentConfig);
Looks like a typo

2024-06-13 12:55 UTC, skurnevich commented on src/actions/InstallationHandler.ts
> +            this.mergeYamlAndInstallationArgs(yamlObj, installationArgs);
Is there a reason why we do this merge with installationArgs values one by one, if it should have been done a line above with yamlObj = Object.assign({}, yamlObj, currentConfig); ?

2024-06-13 13:01 UTC, skurnevich commented on src/actions/InstallationHandler.ts
> +  public async smpeGetExampleYamlAndSchemas (
What is different about smpe installation schemas to have this code separately?

2024-06-13 14:53 UTC, skurnevich commented on src/renderer/components/stages/Certificates.tsx
> +  const [STAGE_ID] = useState(getStageDetails(INIT_STAGE_LABEL).id);
Question on this, we should use useState for variables which we want our component to be re-rendered on change.  Why use it for constants that aren't change in scope of this component?

2024-06-13 15:19 UTC, skurnevich requested changes, later dismissed

2024-06-13 15:19 UTC, skurnevich commented on src/renderer/components/stages/Networking.tsx
> +const schema: any = {
What about this schema, it is zowe-yaml-schema.json right? if we need if for fallback then probably we can move it out to constants, or have fallback schemas just shipped as files with zen?

2024-06-14 01:19 UTC, timgerstel commented on src/actions/InstallationHandler.ts
> +            this.mergeYamlAndInstallationArgs(yamlObj, installationArgs);
At one point, during the very first run of Zen current config did not exist. I haven't confirmed this behavior in a while but in my head i dont think it should ever not exist currently.

2024-06-14 01:27 UTC, timgerstel commented on src/actions/InstallationHandler.ts
> +  public async smpeGetExampleYamlAndSchemas (
Very good point, i changed it to reuse this function in the downloadUnpax function to reduce duplication

2024-06-14 01:29 UTC, timgerstel commented on src/renderer/components/stages/Certificates.tsx
> +  const [STAGE_ID] = useState(getStageDetails(INIT_STAGE_LABEL).id);
> Why use it for constants that aren't change in scope of this component?

If it's not wrapped in useState, react will reinitialize the variable even when the component doesnt rerender I believe. If you put a naked console.log in the global scope of a React component, it will keep getting called over and over. This leak could get costly on memory so I play it safe and wrap everything in useState.

I could also be mistaken about the re-initialization part

2024-06-14 01:31 UTC, timgerstel commented
@skurnevich 

Thank you so much for your review.

>For the last one i have created the https://github.com/zowe/zen/pull/179 to replace cat command output parsing with files downloading.
You can merge it first, or incorporate changes into this PR.

I implemented this code and I love it so much more than doing string manipulations which were unreliable due to the job output not always having the same format for some reason. I implemented it into this PR.

2024-06-14 04:04 UTC, timgerstel commented on src/renderer/components/stages/Networking.tsx
> +const schema: any = {
This schema is actually different than zowe-yaml-schema.json, it hardcodes references from the server-common.json schema because AJV was having trouble resolving references. It also has a few fixes for regexes (zoweDataset, zoweDatasetMember) that AJV did not like

2024-06-14 04:16 UTC, timgerstel commented on src/renderer/components/stages/Certificates.tsx
> +  const [STAGE_ID] = useState(getStageDetails(INIT_STAGE_LABEL).id);
I think I was mistaken about these variables needing to be in useState

2024-06-14 16:58 UTC, skurnevich commented on src/actions/InstallationHandler.ts
> +              yamlObj = Object.assign({}, yamlObj, currentConfig);
This bug comes from here
`18:45:09.025 › error parsing example-zowe.yaml: TypeError: Cannot set properties of undefined (setting 'name')`
Object.assign replaces complete zowe section so some default properties disappear, we should use some deep merge algorithm, we can use some external lib, but i would recommend to avoid adding more dependencies and would just use some recursive func like this:
```
function deepMerge(base, extension) {
  if (isObject(base) && isObject(extension)) {
    for (const key in extension) {
      if (isObject(extension[key])) {
        if (!base[key]) base[key] = {};
        deepMerge(base[key], extension[key]);
      } else {
        Object.assign(base, {[key]: extension[key]});
      }
    }
  }
  return base;
}
```

2024-06-14 21:29 UTC, timgerstel commented on src/actions/InstallationHandler.ts
> +              yamlObj = Object.assign({}, yamlObj, currentConfig);
Added this, another great suggestion. Really appreciate your review on this massive PR!

2024-06-21 09:33 UTC, skurnevich commented
Hi @timgerstel is this PR ready for review/merge or would you like to add more changes?

2024-06-24 02:13 UTC, DivergentEuropeans commented
Created PR: https://github.com/zowe/zen/pull/194

2024-06-26 21:36 UTC, DivergentEuropeans commented on src/main/index.ts
> +    const res = await installActions.smpeGetExampleYamlAndSchemas(connectionArgs, installationArgs);
shouldn't this be called "getExampleYamlAndSchemas"

I only see this used in 2 places, 1 in Stepper which is conditional to not SMPE and 2 in 
Unpax step which is also not SMPE

2024-06-26 21:36 UTC, DivergentEuropeans commented on src/renderer/components/Home.tsx
> +        const flattenedData = flatten(lastActiveState);
`lastActiveState `is already a flat object with no nested properties, at a quick glance, don't see it set anywhere. Is this essential?

2024-06-26 21:36 UTC, DivergentEuropeans commented on src/renderer/components/Home.tsx
> +    //Home is the first screen the user will always see 100% of the time. Therefore, we will call the loading of the configs, schemas, and installation args here and set them to the redux memory stat
Makes sense 👍

2024-06-26 21:36 UTC, DivergentEuropeans commented on src/renderer/components/Home.tsx
> +    //Home is the first screen the user will always see 100% of the time. Therefore, we will call the loading of the configs, schemas, and installation args here and set them to the redux memory stat
Home.tsx change is v satisfying

2024-06-26 21:36 UTC, DivergentEuropeans commented on src/renderer/components/common/EditorDialog.tsx
> +    setIsSchemaValid(!schemaValidate.errors);
N i c e

2024-06-26 21:36 UTC, DivergentEuropeans commented on src/renderer/components/stages/Certificates.tsx
> +  const [STAGE_ID] = useState(getStageDetails(INIT_STAGE_LABEL).id);
I haven't tested it, but I think @timgerstel might be right here. Not that you're wrong @skurnevich , I think both things are true: using const with useState introduces a small overhead. So it would be like:
For constants and simple values that do not involve expensive computation, use them directly without useState.
For values that involve expensive computation or need to persist across renders, use useState.

So something like this might be max/minning:
```
const Certificates = () => {
  const theme = useState(createTheme())[0]; // Expensive
  const stageLabel = 'Initialization';
  const STAGE_ID = useState(getStageDetails(INIT_STAGE_LABEL).id)[0]; // Potentially expensive?
};
```

2024-06-26 21:36 UTC, DivergentEuropeans commented on src/renderer/components/stages/Certificates.tsx
> +  const [validate] = useState(() => ajv.getSchema("https://zowe.org/schemas/v2/server-base") || ajv.compile(setupSchema))
V nitpick but all of these `https://zowe.org/schemas/v2/server-base` should be Constants.BASE_SCHEMA.$id

2024-06-26 21:36 UTC, DivergentEuropeans commented on src/renderer/components/stages/Certificates.tsx
> +      if(!res.status){
This may be unfinished. Not that it's relevant to this PR, it's already a large and good one, but in other steps to correctly determine if we need toggleEditor, we need checks for script failure status, res.status is unreliable. Something like,

```if (res?.details && res.details.jobOutput.indexOf(JCL_UNIX_SCRIPT_OK) == -1) {```

Not sure if you had a chance to test all those res.status cases. I would have res.status = 0, but the command failed. TODO for a later PR could be fine

2024-06-26 21:36 UTC, DivergentEuropeans commented on src/renderer/components/stages/InitApfAuth.tsx
> +        window.electron.ipcRenderer.setStandardOutput(`zwe init apfauth failed:  ${typeof err === "string" ? err : err.toString()}`).then((res: any) => {
If this was tested, then you want to add:
`alertEmitter.emit('showAlert', 'Please view Job Output for more details', 'error');`

2024-06-26 21:36 UTC, DivergentEuropeans commented on src/renderer/components/stages/Networking.tsx
> +const schema: any = {
So if BASE_SCHEMA is AJV "fixed", can't we remove the schemas in Networking + Launch Config and use BASE_SCHEMA? Or lmk I might be missing something

2024-06-26 21:36 UTC, DivergentEuropeans commented on src/renderer/components/stages/Networking.tsx
> +          </div>
This whole chunk is difficult to rea dfor me, but it looks mostly like a "code move" so it seems alright

2024-06-26 21:36 UTC, DivergentEuropeans commented on src/renderer/components/stages/Security.tsx
> +      window.electron.ipcRenderer.setStandardOutput(`zwe init security failed:  ${typeof err === "string" ? err : err.toString()}`).then((res: any) => {
If this was tested, then you want to add:
alertEmitter.emit('showAlert', 'Please view Job Output for more details', 'error');

2024-06-26 21:36 UTC, DivergentEuropeans commented on src/renderer/components/stages/installation/Installation.tsx
> +        if (!res.status && res?.details && res.details[3] && res.details[3].indexOf(JCL_UNIX_SCRIPT_OK) == -1) { // This check means we got an error during zwe install
I don't think this is a good addition. I remember cases where res.status = 0, yet the command failed. That was the whole point of using 'JCL_UNIX_SCRIPT_OK' as a better source of truth over status

2024-06-26 21:36 UTC, DivergentEuropeans commented on src/renderer/components/stages/Unpax.tsx
> +      if(!res.status){ //errors during runInstallation()
Same point here about unreliability of res.status

2024-06-26 21:37 UTC, DivergentEuropeans commented on src/renderer/components/common/EditorDialog.tsx
> +    setIsSchemaValid(!schemaValidate.errors);
that all that adjv stuff worked

2024-06-27 13:01 UTC, DivergentEuropeans approved these changes

2024-06-27 16:32 UTC, skurnevich commented on src/renderer/components/stages/Certificates.tsx
> +  const [STAGE_ID] = useState(getStageDetails(INIT_STAGE_LABEL).id);
No worries, @DivergentEuropeans, that was more like a question from my side. 
So you say that in this case:
`const [STAGE_ID] = useState(getStageDetails(INIT_STAGE_LABEL).id)`
`getStageDetails` function will be triggered less times than in this case: 
`const STAGE_ID = getStageDetails(INIT_STAGE_LABEL).id`
Right? Or it will bring some other performance changes? 

I am asking because i've never seen such usage before. 
For caching really expensive operations i get used to use "useMemo"

2024-06-27 20:25 UTC, merged

2024-07-02 19:29 UTC, timgerstel commented on src/renderer/components/Home.tsx
> +        const flattenedData = flatten(lastActiveState);
yeah youre right but that's pretty minor i dont that one time call when the user clicks "new installation" would cause a noticeable performance impact

2024-07-02 19:29 UTC, timgerstel commented on src/renderer/components/stages/Certificates.tsx
> +  const [validate] = useState(() => ajv.getSchema("https://zowe.org/schemas/v2/server-base") || ajv.compile(setupSchema))
they could all be replaced yes

2024-07-02 19:31 UTC, timgerstel commented on src/renderer/components/stages/InitApfAuth.tsx
> +        window.electron.ipcRenderer.setStandardOutput(`zwe init apfauth failed:  ${typeof err === "string" ? err : err.toString()}`).then((res: any) => {
That is redundant because the editor automatically pops up we don't need a popup to tell the user to look at the output that they are already looking at

2024-07-02 19:31 UTC, timgerstel commented on src/renderer/components/stages/Security.tsx
> +      window.electron.ipcRenderer.setStandardOutput(`zwe init security failed:  ${typeof err === "string" ? err : err.toString()}`).then((res: any) => {
>So if BASE_SCHEMA is AJV "fixed", can't we remove the schemas in Networking + Launch Config and use BASE_SCHEMA? Or lmk I might be missing something

2024-07-02 19:32 UTC, timgerstel commented on src/main/index.ts
> +    const res = await installActions.smpeGetExampleYamlAndSchemas(connectionArgs, installationArgs);
sure