Regression - vsam status
zowe/zen pull request #193
Opened 2024-06-18 13:19 UTC by sakshibobade21

## Proposed changes

This PR addresses Issue: This PR resolves the regression where the status for the vsam stage is updated without stage completion

This PR depends upon the following PRs:

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Change in a documentation
- [ ] Refactor the code 
- [ ] Chore, repository cleanup, updates the dependencies.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## PR Checklist
Please delete options that are not relevant.
- [ ] If the changes in this PR are meant for the next release / mainline, this PR targets a "staging" branch.
- [ ] My code follows the style guidelines of this project (see: [Contributing guideline](https://github.com/zowe/zen/blob/v2.x/staging/CONTRIBUTING.md))
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes
- [ ] video or image is included if visual changes are made

- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works, or describe a test method below

## Testing

## Further comments

2024-06-21 00:15 UTC, timgerstel approved these changes

2024-06-21 00:15 UTC, timgerstel commented on src/renderer/components/common/Stepper.tsx
> +    if ((isSubStep && getProgress(stages[stageId].subStages[subStepId].statusKey)) || (!isSubStep && getProgress(stages[stageId].statusKey))) {
Wait why dont we want to check for error

2024-06-26 14:23 UTC, sakshibobade21 commented on src/renderer/components/common/Stepper.tsx
> +    if ((isSubStep && getProgress(stages[stageId].subStages[subStepId].statusKey)) || (!isSubStep && getProgress(stages[stageId].statusKey))) {
We no longer need the "error" prop. We show the warning icon depending on the skip status of the stage.

2024-06-26 14:38 UTC, timgerstel commented on src/renderer/components/stages/progress/StageProgressStatus.ts
> +  setStageSkipStatus(stepSkipKeysArray[stageId-1], value);
this needs a check to make sure stageId isn't an out of bounds index

2024-06-26 14:38 UTC, timgerstel commented on src/renderer/components/stages/progress/StageProgressStatus.ts
> +  return skipStatusArray[subStageId-1];
check if array index out of bounds

2024-06-26 14:39 UTC, timgerstel commented on src/renderer/components/common/Stepper.tsx
> +    if ((isSubStep && getProgress(stages[stageId].subStages[subStepId].statusKey)) || (!isSubStep && getProgress(stages[stageId].statusKey))) {
Should probably remove the arg then if its not needed

2024-06-26 14:58 UTC, sakshibobade21 commented on src/renderer/components/common/Stepper.tsx
> +    if ((isSubStep && getProgress(stages[stageId].subStages[subStepId].statusKey)) || (!isSubStep && getProgress(stages[stageId].statusKey))) {
Yes it is removed.

2024-06-27 06:40 UTC, sakshibobade21 commented on src/renderer/components/stages/progress/StageProgressStatus.ts
> +  setStageSkipStatus(stepSkipKeysArray[stageId-1], value);
Done. Thanks

2024-06-27 06:41 UTC, sakshibobade21 commented on src/renderer/components/stages/progress/StageProgressStatus.ts
> +  return skipStatusArray[subStageId-1];
Done. Thanks

2024-07-01 13:47 UTC, DivergentEuropeans commented on src/renderer/components/stages/Security.tsx
> -      stages[STAGE_ID].isSkipped = true;
Can you explain these changes a bit more? So why are we removing some of these skipped statuses when things fail? We don't want them to successful, and if they are green, and are re-run and they fail, status should go from green to skipped no? (well ideally "error" status but it's nbd)

2024-07-01 13:47 UTC, DivergentEuropeans commented on src/renderer/components/stages/Networking.tsx
> -    stages[STAGE_ID].isSkipped = isInitializationSkipped;
My comment applies here too

2024-07-01 13:47 UTC, DivergentEuropeans commented on src/renderer/components/stages/InitApfAuth.tsx
> -        stages[STAGE_ID].isSkipped = true;
My comment applies here too

2024-07-01 13:47 UTC, DivergentEuropeans commented on src/renderer/components/stages/installation/Installation.tsx
> -        stages[STAGE_ID].isSkipped = true;
Here too, etc. etc.

2024-07-01 13:47 UTC, DivergentEuropeans commented on src/renderer/components/stages/installation/Installation.tsx
> -        stages[STAGE_ID].isSkipped = true;
Also did you mean to remove 'installProceedActions' too?

2024-07-01 13:47 UTC, DivergentEuropeans commented on src/renderer/components/stages/Certificates.tsx
> +    mapAndSetSubStepSkipStatus(SUB_STAGE_ID, status);
If we have `stages` which is state, and we can set both status for the main step and sub step, so looks like we need a `mapAndSetSubStepSkipStatus` for setting local storage, ok sure

but I think
 a) this method should be renamed to like "setAndSaveSubStepSkipStatus"/"setAndStoreSubStepSkipStatus" and "setAndSaveStepSkipStatus"/"setAndStoreStepSkipStatus" because it's doing a storage operation
 b) if these methods already do the setting, why do we need `stages[STAGE_ID].xxxx` stuff at all, shouldn't it be removed
 c) doesn't need to be this PR, but why is `StageProgressStatus.ts` not using a Store?

2024-07-02 05:29 UTC, sakshibobade21 commented on src/renderer/components/stages/Security.tsx
> -      stages[STAGE_ID].isSkipped = true;
If things fail, we call updateProgress(false). Update progress internally calls setStageSkipStatus(true) which sets the status for the stages.

2024-07-02 05:30 UTC, sakshibobade21 commented on src/renderer/components/stages/Security.tsx
> -      stages[STAGE_ID].isSkipped = true;
This changes were made to cleanup the code and remove redundant lines of code

2024-07-02 05:30 UTC, sakshibobade21 commented on src/renderer/components/stages/Networking.tsx
> -    stages[STAGE_ID].isSkipped = isInitializationSkipped;
If things fail, we call updateProgress(false). Update progress internally calls setStageSkipStatus(true) which sets the status for the stages.

This changes were made to cleanup the code and remove redundant lines of code

2024-07-02 05:37 UTC, sakshibobade21 commented on src/renderer/components/stages/installation/Installation.tsx
> -        stages[STAGE_ID].isSkipped = true;
Removed `installProceedActions()` because updateProgress() is calling it internally.

Again this change was made to cleanup the code and remove redundant lines of code

2024-07-02 05:52 UTC, sakshibobade21 commented on src/renderer/components/stages/Certificates.tsx
> +    mapAndSetSubStepSkipStatus(SUB_STAGE_ID, status);
The function mapAndSetSubStepSkipStatus() is used to update the local storage. stages[STAGE_ID].xxxx modifies the state only for the current session. When the user resumes, we utilize mapAndGetSubStepSkipStatus() to update stage[stage_id].skip.

Throughout the session, stages[STAGE_ID].skip is used to retrieve and update the status. While mapAndGetSubStepSkipStatus() is useful for fetching status, doing so from local storage every time could impact performance negatively.

2024-07-02 05:55 UTC, sakshibobade21 commented on src/renderer/components/stages/Certificates.tsx
> +    mapAndSetSubStepSkipStatus(SUB_STAGE_ID, status);
I agree with you; there is indeed scope for code cleanup and improvement here. We can simplify by calling mapAndSetSubStepSkipStatus(). Within this function, we can set stages[STAGE_ID].skip and update the local storage.

Could we handle the code cleanup in a separate PR?

2024-07-02 06:01 UTC, sakshibobade21 commented on src/renderer/components/stages/Certificates.tsx
> +    mapAndSetSubStepSkipStatus(SUB_STAGE_ID, status);
We also have` mapAndSetStepSkipStatus()` for stages.
I can rename these to `setAndSaveSubStepSkipStatus` but we already have `setSubStageSkipStatus`.
`mapAndSetSubStepSkipStatus` calls `setSubStageSkipStatus` by passing the `stageid` and the `status`.

2024-07-02 18:47 UTC, DivergentEuropeans commented on src/renderer/components/stages/Certificates.tsx
> +    mapAndSetSubStepSkipStatus(SUB_STAGE_ID, status);
> While mapAndGetSubStepSkipStatus() is useful for fetching status, doing so from local storage every time could impact performance negatively.

This is mostly irrelevant because we (should) only update the status after button clicks & operations. If this is negatively affecting performance, that means we are calling it during each render operation which points to an issue elsewhere

> I agree with you; there is indeed scope for code cleanup and improvement here. We can simplify by calling mapAndSetSubStepSkipStatus().

Yes, let's move forward with that and I would prefer to have it done in this PR because you already started some of that duplication removal. So just continue that for everywhere, or do it in a separate PR, but don't begin it & then leave it unfinished (unless you write a detailed TODO)

Rename sounds good 👍 setSubStageSkipStatus and setAndStoreSubStepSkipStatus / setAndSaveSubStepSkipStatus both sound good and make sense, for what they are titled for

2024-07-02 18:53 UTC, DivergentEuropeans commented on src/renderer/components/stages/Certificates.tsx
> +    mapAndSetSubStepSkipStatus(SUB_STAGE_ID, status);
If your setAndSave methods work properly, then the refactor is just a text search and replace so I would prefer it done in the same PR

2024-07-02 18:54 UTC, DivergentEuropeans commented on src/renderer/components/stages/Networking.tsx
> -    stages[STAGE_ID].isSkipped = isInitializationSkipped;
Where do we call it near this code? Not called in this file at least

2024-07-02 19:40 UTC, DivergentEuropeans commented on src/renderer/components/stages/Certificates.tsx
> +    mapAndSetSubStepSkipStatus(SUB_STAGE_ID, status);
Then you would want to check for performance hits, by seeing if the useEffect( )'s or whatever are called after significant necessary updates versus each re-render. It could be out of scope to FIX all the performance hits, but what it means is:
some methods will have
```
stages[STAGE_ID].subStages[SUB_STAGE_ID].isSkipped = status;
    stages[STAGE_ID].isSkipped = status;
```


bla bla bla right, some methods will have
```
mapAndSetSubStepSkipStatus(SUB_STAGE_ID, status);
```

but no methods should have BOTH

2024-07-03 04:16 UTC, sakshibobade21 commented on src/renderer/components/stages/Networking.tsx
> -    stages[STAGE_ID].isSkipped = isInitializationSkipped;
I removed those lines of code because every time the networking component loads, it incorrectly sets the `skip` status to true. If the networking stage is successfully completed and the user revisits it, the status should be  completed, not skipped.

2024-07-03 04:16 UTC, sakshibobade21 commented on src/renderer/components/stages/Networking.tsx
> -    stages[STAGE_ID].isSkipped = isInitializationSkipped;
Same applies for the launch config stage

2024-07-03 04:48 UTC, sakshibobade21 commented on src/renderer/components/stages/Certificates.tsx
> +    mapAndSetSubStepSkipStatus(SUB_STAGE_ID, status);
We have

 ```
const setStageSkipStatus = (status: boolean) => {
    stages[STAGE_ID].subStages[SUB_STAGE_ID].isSkipped = status;
    stages[STAGE_ID].isSkipped = status;
    mapAndSetSubStepSkipStatus(SUB_STAGE_ID, status);
  }
```

`.isSkipped` is just updating the stages array.
And `mapAndSetSubStepSkipStatus` is updating the local storage.

We can move below code
```
stages[STAGE_ID].subStages[SUB_STAGE_ID].isSkipped = status;
stages[STAGE_ID].isSkipped = status;
```

inside `mapAndSetSubStepSkipStatus`. But I think it is better we keep them separated.

2024-07-03 06:16 UTC, sakshibobade21 commented on src/renderer/components/stages/Certificates.tsx
> +    mapAndSetSubStepSkipStatus(SUB_STAGE_ID, status);
I will try to address the performance improvements in the same PR.

2024-07-03 06:20 UTC, sakshibobade21 commented on src/renderer/components/stages/Certificates.tsx
> +    mapAndSetSubStepSkipStatus(SUB_STAGE_ID, status);
We have
```
const setStageSkipStatus = (status: boolean) => {
   stages[STAGE_ID].subStages[SUB_STAGE_ID].isSkipped = status;
   stages[STAGE_ID].isSkipped = status;
   mapAndSetSubStepSkipStatus(SUB_STAGE_ID, status);
 }
```
`.isSkipped` is just updating the stages array and not the local storage.
And `mapAndSetSubStepSkipStatus` is updating the local storage.

We need to update both.

2024-07-03 16:54 UTC, sakshibobade21 commented
@DivergentEuropeans I addressed all possible code cleanups, both related and unrelated to the stage statuses. I also tried to optimized performance by minimizing calls to functions that interact with local storage, such that these functions are called only once when the component unmounts. Additionally, I renamed the functions we discussed earlier.

2024-07-05 15:30 UTC, DivergentEuropeans requested changes, later dismissed

2024-07-05 15:30 UTC, DivergentEuropeans commented on src/renderer/components/common/Stepper.tsx
> +  }
I am a bit confused by this change. So originally, we set `isNextSStepEnabled` based on useAppSelector(selectNextStepEnabled) which comes from the `setNextStepEnabled` state which is a thing where steps have logic to signal if next step is enabled, based on if a certain action has been performed. Ok, sure. 

But now, we are moving away from this to --> check for a `getProgress` which comes from local storage, where a status is being set based on logic within steps upon status completion.

a) So if case 1's state is no longer needed, why don't we remove it? 

b) Why is it called "getProgress"/"setProgress" instead of "get/setStatus" ? 

c) StageProgressStatus.ts in my opinion is a bit long and over-engineered and difficult to read. I think I approved a smaller, earlier version of it many months ago but this was a big mistake. Why are there useless keys there like, 
`let installationTypeKey = 'installation_type';` when this could be 
`INSTALLATION_TYPE_STAGE_LABEL` from Utils.tsx (which was previously just a const in a home/main page somewhere)

You don't need to do anything with c) in this PR

2024-07-05 15:30 UTC, DivergentEuropeans commented on src/renderer/components/common/Stepper.tsx
> +  }
And btw for c) I'm not talking about localstorage vs redux. That's fine that we used local storage, but the file is still unnecessarily difficult to read

2024-07-05 15:30 UTC, DivergentEuropeans commented on src/renderer/components/stages/Certificates.tsx
> +    dispatch(setNextStepEnabled(status));
If we are now using "Status" as the signal that tells us if next step is enabled, then all of these `setNextStepEnabled` now become useless no?

2024-07-08 09:42 UTC, sakshibobade21 commented on src/renderer/components/stages/Certificates.tsx
> +    dispatch(setNextStepEnabled(status));
Himani identified an issue in my pull request: the next step was not enabled during the unpax stage when the stage was completed.
While debugging, I discovered that the nextStepButtonDisabled function was being called multiple times, even when the stage status remained unchanged. This caused the data to be fetched from local storage repeatedly. Although this didn't significantly impact performance, it would be more efficient to use the setNextStepEnabled function instead.
Therefore, I updated the code to use setNextStepEnabled, along with some modifications.

2024-07-08 09:42 UTC, sakshibobade21 commented on src/renderer/components/common/Stepper.tsx
> +  }
Himani identified an issue in my pull request: the next step was not enabled during the unpax stage when the stage was completed.
While debugging, I discovered that the nextStepButtonDisabled function was being called multiple times, even when the stage status remained unchanged. This caused the data to be fetched from local storage repeatedly. Although this didn't significantly impact performance, it would be more efficient to use the setNextStepEnabled function instead.
Therefore, I updated the code to use setNextStepEnabled, along with some modifications.

2024-08-01 16:49 UTC, skurnevich approved these changes
So in the current state we do not distinguish between failed and skipped steps?  

Also, for instance if Certificates step fails - it shows job output as error, but then we skip it and go to vsam (which should be completely optional) and it fails too - it will show error in the header, and the job log stays from the previous failure in Certificates. It looks inconsistent and misleading. 

I do not ming merging this though, as it doesn't break things and in order to continue the development process.

2024-08-05 08:10 UTC, sakshibobade21 commented on src/renderer/components/stages/Certificates.tsx
> +    dispatch(setNextStepEnabled(status));
Addressed - https://github.com/zowe/zen/pull/193#discussion_r1668324613

2024-08-05 08:24 UTC, sakshibobade21 commented
@skurnevich Thank you for reviewing the PR.

At present, in ZEN, we do not differentiate between failed and skipped steps. This could be a potential enhancement to consider for future improvements.

Regarding your comment about the certificate stage, I think we should address that in a separate PR since it originates from the staging. I will create a ticket for this.

Thanls.

2024-08-05 11:19 UTC, skurnevich commented
Hi Sakshi, that is fine with me, please resolve Lenny's changes request and we can merge this PR

2024-08-06 07:00 UTC, sakshibobade21 commented
@skurnevich thanks. And the changes requested by Lenny have already been addressed.

2024-08-06 09:45 UTC, skurnevich commented
Hi @sakshibobade21 , i'll merge this PR, but problem is the github still has "Changes requested" as blocker for merge there.
<img width="907" alt="Screenshot 2024-08-06 at 11 11 15" src="https://github.com/user-attachments/assets/29cbb913-aef3-4c37-bb38-88999dd6db7f">
As far as i can see the requests were addressed, and I can merge it bypassing the protection if @DivergentEuropeans  does not mind. 
But the proper way to resolve this is to re-request review, 
<img width="399" alt="Screenshot 2024-08-06 at 11 25 24" src="https://github.com/user-attachments/assets/a50ddd5a-d75c-47df-ab53-86294057591b">
Github sometimes acts weird with permissions, so can you please check if you have this option in the top right corner first?

2024-08-06 09:50 UTC, sakshibobade21 commented
@skurnevich I re-requested the review. Hope that works.
Thank you.

2024-08-09 00:19 UTC, DivergentEuropeans commented
Thanks, dismissed stale review @sakshibobade21 @skurnevich

2024-08-09 11:01 UTC, merged