Dataset Validation On Installation Stage
zowe/zen pull request #233
Opened 2024-07-29 14:40 UTC by sakshibobade21

## Proposed changes

This PR addresses Issue: This PR adds the dataset validations on the installation stage

This PR depends upon the following PRs:

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Change in a documentation
- [ ] Refactor the code 
- [ ] Chore, repository cleanup, updates the dependencies.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## PR Checklist
Please delete options that are not relevant.
- [ ] If the changes in this PR are meant for the next release / mainline, this PR targets a "staging" branch.
- [ ] My code follows the style guidelines of this project (see: [Contributing guideline](https://github.com/zowe/zen/blob/v2.x/staging/CONTRIBUTING.md))
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes
- [ ] video or image is included if visual changes are made

- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works, or describe a test method below

## Testing

## Further comments

2024-08-06 18:26 UTC, skurnevich requested changes

2024-08-06 18:26 UTC, skurnevich commented on src/renderer/components/stages/installation/Installation.tsx
> +      if (typeof value === 'object' && value !== null) {
I guess this part is hardcoded to the current state of zowe.yaml, assuming that there is just one value in the parmlibMembers object - {zis: ZWESIP00}. 
If we add one more value there later it would not be validated, so instead we should recursively go to validateDatasets with that new object or flatten data

2024-08-06 18:26 UTC, skurnevich commented on src/renderer/components/stages/installation/Installation.tsx
> +    if(Object.keys(setupYaml).length < 8) {
Same here, now we have 8 values there but it can easily change, moreover for instance zowe.setup.dataset.authLoadlib is actually optional. 
This better to be controlled by schema, but i can't see it for zowe.setup.dataset, so i guess for now we can remove hardcoded numbers and just validate it in the UI by not allowing empty values?

2024-08-06 18:26 UTC, skurnevich commented on src/renderer/components/stages/installation/Installation.tsx
> +              <ErrorIcon color="error" sx={{ fontSize: 20 }}/>
I thought we have some unified errors popup in the header? why we have different approach here?

2024-08-07 14:40 UTC, sakshibobade21 commented on src/renderer/components/stages/installation/Installation.tsx
> +      if (typeof value === 'object' && value !== null) {
Updates this. Thank you.

2024-08-07 14:40 UTC, sakshibobade21 commented on src/renderer/components/stages/installation/Installation.tsx
> +    if(Object.keys(setupYaml).length < 8) {
Addressed these changes. Thank you.

2024-08-07 14:42 UTC, sakshibobade21 commented on src/renderer/components/stages/installation/Installation.tsx
> +              <ErrorIcon color="error" sx={{ fontSize: 20 }}/>
I initially considered displaying the form errors right below the form after clicking "Install MVS Datasets." However, let's stick to using the unified error messages in the header instead.

Update this. Thank you.

2024-08-07 18:43 UTC, skurnevich approved these changes
LGTM, however, in future i would prefer it to be validated via schema like https://github.com/zowe/zowe-install-packaging/blob/v2.x/staging/schemas/server-common.json#L39 
But we need to update schema for that

2024-08-08 08:59 UTC, merged