[WIP]ZEN Bugfix for the Schema Updates
zowe/zen pull request #237
Opened 2024-08-01 12:25 UTC by sakshibobade21

## Proposed changes

This PR addresses Issue: [*Link to Github issue within https://github.com/zowe/zen/issues* if any]

This PR depends upon the following PRs:

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Change in a documentation
- [ ] Refactor the code 
- [ ] Chore, repository cleanup, updates the dependencies.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## PR Checklist
Please delete options that are not relevant.
- [ ] If the changes in this PR are meant for the next release / mainline, this PR targets a "staging" branch.
- [ ] My code follows the style guidelines of this project (see: [Contributing guideline](https://github.com/zowe/zen/blob/v2.x/staging/CONTRIBUTING.md))
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes
- [ ] video or image is included if visual changes are made

- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works, or describe a test method below

## Testing

## Further comments

2024-08-01 13:09 UTC, timgerstel commented on src/actions/InstallationHandler.ts
> +                  filteredArray[0].properties.pkcs12.properties.directory = serverCommon.$defs.path;
This looks like it will correctly set the directory definition, but the original yamlSchema object needs to be updated too since filteredArray is a separate variable.

2024-08-01 16:59 UTC, 1000TurquoisePogs requested changes

2024-08-01 16:59 UTC, 1000TurquoisePogs commented on src/actions/InstallationHandler.ts
> +                yamlSchema.properties.zowe.properties.setup.properties.certificate.properties.pkcs12.properties.directory = serverCommon.$defs.path;
why is the schema being modified?
this will only lead to disappointment, such as the break we see in v2.17
there will be more in the future.
don't edit the schema, and it wont break.

2024-08-01 17:20 UTC, sakshibobade21 commented on src/actions/InstallationHandler.ts
> +                  filteredArray[0].properties.pkcs12.properties.directory = serverCommon.$defs.path;
Updating the filteredArray will also update yamlSchema because filteredArray contains references to objects within the yamlSchema structure.
What you are saying is valid for the primitive values.

2024-08-01 17:21 UTC, sakshibobade21 commented on src/actions/InstallationHandler.ts
> +                yamlSchema.properties.zowe.properties.setup.properties.certificate.properties.pkcs12.properties.directory = serverCommon.$defs.path;
The code is not modifying the schema. It is only setting the reference for `pkcs12.directory`

2024-08-01 20:52 UTC, timgerstel commented on src/actions/InstallationHandler.ts
> +                  filteredArray[0].properties.pkcs12.properties.directory = serverCommon.$defs.path;
Just tested that out you are correct👍

2024-08-02 13:31 UTC, 1000TurquoisePogs commented on src/actions/InstallationHandler.ts
> +                yamlSchema.properties.zowe.properties.setup.properties.certificate.properties.pkcs12.properties.directory = serverCommon.$defs.path;
When you consider that this is doing a $ref resolve https://github.com/zowe/zowe-install-packaging/blob/1f9ad776820f62672d7b3e17d64ef8b9b0569332/schemas/zowe-yaml-schema.json#L176C62-L176C70 then I think a better way to prevent it from breaking in the future is to recurse over the entire `yamlSchema` object looking for keys with name `$ref` and then doing a swap of their values depending on what the value is.
The value `...#` is the `$anchor` property value of another object.

2024-08-06 13:13 UTC, skurnevich commented on src/actions/InstallationHandler.ts
> +                  filteredArray[0].properties.pkcs12.properties.directory = serverCommon.$defs.path;
Even while this is working, it is still a poor approach, it does mutate an object and does it in an unobvious way, in the best case scenario - code just becomes less readable, worst case it may later lead to some bugs that are really hard to spot. 
I would recommend to use some setter function, but i guess this part is not applicable anymore as this code should be gone in final version where we map all the $refs for the entire yamlSchema object in advance, is that correct?

2024-08-09 09:25 UTC, sakshibobade21 commented on src/actions/InstallationHandler.ts
> +                  filteredArray[0].properties.pkcs12.properties.directory = serverCommon.$defs.path;
@skurnevich here is the PR to address this issue - https://github.com/zowe/zen/pull/240
Thanks.

2024-08-21 14:34 UTC, closed without merging