[WIP Not Ready For Review Yet] Handling Schema Updates
zowe/zen pull request #240
Opened 2024-08-09 05:34 UTC by sakshibobade21

## Proposed changes

This PR addresses Issue: [*Link to Github issue within https://github.com/zowe/zen/issues* if any]

This PR depends upon the following PRs:

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Change in a documentation
- [ ] Refactor the code 
- [ ] Chore, repository cleanup, updates the dependencies.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## PR Checklist
Please delete options that are not relevant.
- [ ] If the changes in this PR are meant for the next release / mainline, this PR targets a "staging" branch.
- [ ] My code follows the style guidelines of this project (see: [Contributing guideline](https://github.com/zowe/zen/blob/v2.x/staging/CONTRIBUTING.md))
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes
- [ ] video or image is included if visual changes are made

- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works, or describe a test method below

## Testing

## Further comments

2024-08-09 12:54 UTC, 1000TurquoisePogs approved these changes
Looks like a good long term solution.

2024-08-09 13:26 UTC, skurnevich commented on src/services/ResolveRef.ts
> +    let result = serverCommon.$defs;
So we are resolving only server-common references? I do not know how likely we will have references to other schemas in future but we'd better handle it at least through log / warnings if some refs were not resolved. 
Also how are internal refs handled now, like `"$ref": "#/$defs/pkcs12-certificate"`?

2024-08-09 13:29 UTC, 1000TurquoisePogs commented on src/services/ResolveRef.ts
> +    let result = serverCommon.$defs;
It looks like it would be better to do
const refParts = ref.split('#');

const refFile = refParts[0];
const refAnchor = refParts[1];

if (!refFile) { refFile = zowe-yaml-schema.json }
else { // gather the $id values of each schema file and make a map so you can identify which schema file is being referenced }

2024-08-23 12:36 UTC, skurnevich requested changes

2024-08-23 12:36 UTC, skurnevich commented on src/services/ResolveRef.ts
> +    if(schema !== schemaObject) {
This is an invalid comparison of objects, this will always return true as objects are equal only when both are just pointers to the same object. Luckily we do not have to compare objects here, we can compare schema id's like `schema?.$id !== schemaObject?.$id`

2024-08-23 12:36 UTC, skurnevich commented on src/actions/InstallationHandler.ts
> +            updateSchemaReferences(readPaxYamlAndSchema.details, yamlSchema);
First argument to that function looks odd. You are passing {yaml, yaml-schema and server-schema} as the first argument, then you provide the yaml-schema again as the second argument as a base schema, and then you do a number of checks inside of the func and throwing an error for yaml `Error parsing schema for key yaml: Unexpected token '#', "##########"... is not valid JSON`. 
You have control over the `readExampleYamlAndSchema` function in the same file. It returns the config and schemas altogether for simplicity, but now when we have different usage for these we can split it in two functions, or at least change returning object to something like 
`{..., details: {yaml: '', schemas: {<schema1.$id>: schema1, <schema2.$id>: schema2}}` 
and then you can simplify the `updateSchemaReferences` as objects will be filtered and the schemaMap will be prepared already.  

Also the `readExampleYamlAndSchema` now returns only two hardcoded schemas, so we will need to update it anyway and take other schemas, but probably we can handle all of above as a separate PR, just need to add an issue to track it.

2024-08-29 12:21 UTC, sakshibobade21 commented on src/actions/InstallationHandler.ts
> +            updateSchemaReferences(readPaxYamlAndSchema.details, yamlSchema);
Thanks @skurnevich 

I would prefer passing schemas as an object containing all the available schemas, rather than using a map like this:

```
{ ..., details: { yaml: '', schemas: { schema1,  schema2 } }}
```

The reason is that if we use a map e.g.: 

```
{ ..., details: { yaml: '', schemas: { [yamlSchema.$id]: yamlSchema, [serverCommon.$id]: serverCommon } }}
```

We would need to maintain a strict sequence to access these schemas because we wouldn't know which schema corresponds to which $id in the code.

```
const schemaIds = Object.keys(readPaxYamlAndSchema.details.schemas);
// Access schemas using their ids
const yamlSchema = readPaxYamlAndSchema.details.schemas[schemaIds[0]];
const serverCommon = readPaxYamlAndSchema.details.schemas[schemaIds[1]];
```

This would unnecessarily complicate the code and make it harder to manage.

Does that sound good to you?

2024-08-29 12:22 UTC, sakshibobade21 commented on src/services/ResolveRef.ts
> +    if(schema !== schemaObject) {
Addressed it. Thank you.

2024-08-29 14:23 UTC, skurnevich approved these changes
Looks good

2024-08-30 12:45 UTC, merged