[WIP] Update JSON Forms
zowe/zen pull request #241
Opened 2024-08-09 10:20 UTC by sakshibobade21

## Proposed changes

This PR addresses Issue: [*Link to Github issue within https://github.com/zowe/zen/issues* if any]

This PR depends upon the following PRs:

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Change in a documentation
- [ ] Refactor the code 
- [ ] Chore, repository cleanup, updates the dependencies.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## PR Checklist
Please delete options that are not relevant.
- [ ] If the changes in this PR are meant for the next release / mainline, this PR targets a "staging" branch.
- [ ] My code follows the style guidelines of this project (see: [Contributing guideline](https://github.com/zowe/zen/blob/v2.x/staging/CONTRIBUTING.md))
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes
- [ ] video or image is included if visual changes are made

- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works, or describe a test method below

## Testing

## Further comments

2024-08-28 15:27 UTC, skurnevich requested changes

2024-08-28 15:27 UTC, skurnevich commented on src/actions/InstallationHandler.ts
> +            updateSchemaReferences(readPaxYamlAndSchema.details, yamlSchema);
Why are we duplicating changes made in https://github.com/zowe/zen/pull/240 here?

2024-08-28 15:27 UTC, skurnevich commented on src/actions/InstallationHandler.ts
> +        return {status: parsedSchema && parsedYaml, details: {message: "Successfully retrieved example-zowe.yaml and schemas", mergedYaml: yamlObj, yamlSchema: yamlSchema}}
Schema is already saved to the ConfigurationStore, lines 162, 169 and 175. 
Then we take yamlSchema that will exist only in successful case (as you only set it in the try block on line 157 and so it will be empty in other cases instead of FALLBACK_SCHEMA)
And then you return it to the UI (Unpax.tsx:180) where use for rendering and override the ConfigurationStore scheme if it exists, which makes not much sense to me, or am i missing something?

2024-08-28 15:27 UTC, skurnevich commented on src/renderer/components/common/JsonForms.tsx
> +const conditionalSchema = (schema: any, formData: any, prop: any): boolean=> {
What reference were you using for this definition? I am looking at https://json-schema.org/understanding-json-schema/reference/conditionals#ifthenelse and it states that `then` or `else` can be omitted, also `then` and `else` sections can have `properties` with pattern, not only `required` field

2024-08-28 15:27 UTC, skurnevich commented on src/renderer/components/common/JsonForms.tsx
> +      {  schema.oneOf &&
General question, can't JSONForms work with "oneOf" out of the box? 
I didn't research much but from [here](https://jsonforms.io/docs/renderer-sets) it seems that is should be supported using tabs?

2024-08-29 12:58 UTC, sakshibobade21 commented on src/actions/InstallationHandler.ts
> +            updateSchemaReferences(readPaxYamlAndSchema.details, yamlSchema);
This PR is built on the top of #240

2024-08-29 14:58 UTC, sakshibobade21 commented on src/actions/InstallationHandler.ts
> +        return {status: parsedSchema && parsedYaml, details: {message: "Successfully retrieved example-zowe.yaml and schemas", mergedYaml: yamlObj, yamlSchema: yamlSchema}}
That's a good catch. Thanks. I fixed it.

2024-08-30 09:07 UTC, sakshibobade21 commented on src/renderer/components/common/JsonForms.tsx
> +const conditionalSchema = (schema: any, formData: any, prop: any): boolean=> {
This section was initially added to handle if-else conditions in the certificate schema for previous versions of Zowe. At that time, we were only verifying whether the conditional attributes were met.

These sections can also contain properties, and while all the properties were displayed, our primary focus was on checking if the condition matched.

2024-08-30 09:20 UTC, sakshibobade21 commented on src/renderer/components/common/JsonForms.tsx
> +      {  schema.oneOf &&
It could work, but we had a slightly different approach in mind:

1. We preferred radio buttons instead of tabs.
2. The JSON form data is stored in YAML, so we needed the YAML to comply with only one schema at a time. For this, we created a function called filterFormData.
3. We also required AJV to validate the data against the correct schema selected from the oneOf schemas.

2024-09-03 14:31 UTC, skurnevich approved these changes
Ok, but please review the comment to InitApfAuth.tsx before merge

2024-09-03 14:31 UTC, skurnevich commented on src/renderer/components/stages/InitApfAuth.tsx
> -    if(validate) {
Why did you remove this validation here? There is unused code block a few lines above, `newData` is never being used, so i wonder if it is not a mistake?

2024-09-03 14:47 UTC, sakshibobade21 commented on src/renderer/components/stages/InitApfAuth.tsx
> -    if(validate) {
I removed this part of the code because it is unnecessary. The APF authorization stage includes read-only fields populated during the previous "Dataset Initialization" stage, where validations for these fields have already been performed. Re-validating them here is redundant.

I also considered removing the formChangeHandler function, as it's no longer required. However, I chose not to do so in this PR to keep the focus solely on the schema updates. I plan to address it in future code optimization PRs.

2024-09-03 20:15 UTC, merged