Schema to Form
zowe/zen pull request #29
Opened 2023-08-17 10:36 UTC by sakshibobade21

This PR is about adding the HTML forms which are dynamically derived from the schema.

2023-08-28 12:51 UTC, 1000TurquoisePogs requested changes

2023-08-28 12:51 UTC, 1000TurquoisePogs commented on src/renderer/components/common/JsonForms.tsx
> +      if(formData && formData.type && ((formData.type != 'PKCS12' && prop == 'pkcs12') || (formData.type == 'PKCS12' && prop == 'keyring'))) {
this is a specific case present in a reusable component.
this cannot be the correct way to solve this problem.
this problem will come up again in other parts of config, so there needs to be a reusable solution.

2023-09-05 16:10 UTC, 1000TurquoisePogs approved these changes
This looks good.

2023-09-14 15:05 UTC, sakshibobade21 commented
Closing this PR. Here is the new one addressing the same concern but with additional features

https://github.com/zowe/zen/pull/43

2023-09-14 15:05 UTC, closed without merging