Release workflow zen
zowe/zen pull request #35
Opened 2023-08-29 06:43 UTC by Himani1519

Github action for release workflow of zen.

2023-09-05 19:42 UTC, 1000TurquoisePogs requested changes
this doesnt appear to work because the `build zen` step is not uploading builds to github, it is uploading them to artifactory.
this script is trying to download from a previous github upload, instead of an artifactory upload.

question is, should the release even have an upload anyway?
i don't think its necessary. skip the zip download & file upload part. the release otherwise publishes the source code i believe, which is enough.

2023-09-05 19:42 UTC, 1000TurquoisePogs commented on .github/workflows/release.yml
> +        run: zip -r zen.zip zen
a zip is here, but what does it contain? i dont think it contains anything actually, because i dont think the `gh run download` has anything to download, because `build zen` doesnt upload anything.

2023-09-05 19:42 UTC, 1000TurquoisePogs commented on .github/workflows/release.yml
> +          files: zen.zip
this would be wrong due to there being no zen.zip

2023-09-06 07:06 UTC, Himani1519 commented
> this doesnt appear to work because the `build zen` step is not uploading builds to github, it is uploading them to artifactory. this script is trying to download from a previous github upload, instead of an artifactory upload.
> 
> question is, should the release even have an upload anyway? i don't think its necessary. skip the zip download & file upload part. the release otherwise publishes the source code i believe, which is enough.

Make sense, I will update the actions

2023-09-12 15:25 UTC, struga0258 approved these changes

2023-09-12 15:25 UTC, struga0258 commented on .github/workflows/release.yml
> +    branches: [main]
we dont have main, we have v2.x/main

2023-09-12 15:25 UTC, struga0258 commented on .github/workflows/release.yml
> +        run: gh run download $(gh run list -w "Build zen" --json databaseId,headBranch,conclusion -q 'map(select(.headBranch == "main")) | map(select(.conclusion == "success")) | .[0].databaseId')
Also here

2023-09-18 13:23 UTC, 1000TurquoisePogs approved these changes

2023-09-18 18:50 UTC, merged