Json Forms And Config Service
zowe/zen pull request #43
Opened 2023-09-14 14:00 UTC by sakshibobade21

1) Adding dynamic html forms derived from the Schema
2) Adding the config service for getter/setters for the subsections of the zowe.yaml. 
3) And integrating this service with the HTML forms dynamically derived from the Schema.

2023-09-15 03:08 UTC, DivergentEuropeans requested changes

2023-09-15 03:08 UTC, DivergentEuropeans commented on src/renderer/components/stages/Certificates.tsx
> +  const setupSchema = schema.properties.zowe.properties.setup.properties.certificate;
This gives me a run-time error because schema.properties doesn't exist

Even if that weren't true, we should still add a validation check when setting variables from big objects 
`?` syntax is fine too

2023-09-15 03:08 UTC, DivergentEuropeans commented on src/renderer/components/stages/Certificates.tsx
> +  const [setupYaml, setSetupYaml] = useState(yaml.zowe.setup.certificate);
Parameter defined check here too

2023-09-15 03:08 UTC, DivergentEuropeans commented on src/renderer/components/stages/Configuration.tsx
> +  const setupSchema = schema.properties.zowe.properties.setup.properties.security;
Parameter defined check here too

2023-09-15 03:08 UTC, DivergentEuropeans commented on src/renderer/components/stages/Configuration.tsx
> +  const [setupYaml, setSetupYaml] = useState(yaml.zowe.setup.security);
Parameter defined check here too

2023-09-15 03:08 UTC, DivergentEuropeans commented on src/renderer/components/stages/installation/Installation.tsx
>    const setupSchema = schema.properties.zowe.properties.setup.properties.dataset;
Parameter defined check here too

2023-09-20 13:07 UTC, sakshibobade21 commented on src/renderer/components/stages/Configuration.tsx
> +  const setupSchema = schema.properties.zowe.properties.setup.properties.security;
@DivergentEuropeans I addressed the changes requested. Thank you

2023-09-25 04:23 UTC, DivergentEuropeans requested changes
I get the following run-time error during Step 5. I ran through all Zen up to this point, skipping nothing, and I selected download from internet option

`[20532:0922/091803.969:INFO:CONSOLE(120)] "Uncaught Error: can't resolve reference /schemas/v2/server-common#zowePath from id #", source: webpack-internal:///./node_modules/@jsonforms/core/node_modules/ajv/dist/compile/index.js (120)
[20532:0922/091803.982:INFO:CONSOLE(18687)] "The above error occurred in the <JsonFormsStateProvider> component:

    at JsonFormsStateProvider (webpack-internal:///./node_modules/@jsonforms/react/lib/jsonforms-react.esm.js:132:35)
    at JsonForms (webpack-internal:///./node_modules/@jsonforms/react/lib/jsonforms-react.esm.js:395:13)
    at InnerThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:23:70)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js:45:5)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:42:5)
    at JsonForm (webpack-internal:///./src/renderer/components/common/JsonForms.tsx:94:13)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Box (webpack-internal:///./node_modules/@mui/system/esm/createBox.js:34:72)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Container (webpack-internal:///./node_modules/@mui/system/esm/Container/createContainer.js:117:19)
    at form
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Box (webpack-internal:///./node_modules/@mui/system/esm/createBox.js:34:72)
    at ContainerCard (webpack-internal:///./src/renderer/components/common/ContainerCard.tsx:28:13)
    at Certificates (webpack-internal:///./src/renderer/components/stages/Certificates.tsx:24:49)
    at div
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Box (webpack-internal:///./node_modules/@mui/system/esm/createBox.js:34:72)
    at HorizontalLinearStepper (webpack-internal:///./src/renderer/components/common/Stepper.tsx:48:13)
    at div
    at Wizard (webpack-internal:///./src/renderer/components/configuration-wizard/Wizard.tsx:35:133)
    at RenderedRoute (webpack-internal:///./node_modules/react-router/dist/index.js:715:5)
    at Outlet (webpack-internal:///./node_modules/react-router/dist/index.js:1118:26)
    at Header
    at RenderedRoute (webpack-internal:///./node_modules/react-router/dist/index.js:715:5)
    at Routes (webpack-internal:///./node_modules/react-router/dist/index.js:1209:5)
    at Router (webpack-internal:///./node_modules/react-router/dist/index.js:1141:15)
    at HashRouter (webpack-internal:///./node_modules/react-router-dom/dist/index.js:372:5)
    at InnerThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:23:70)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js:45:5)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:42:5)
    at Provider (webpack-internal:///./node_modules/react-redux/es/components/Provider.js:16:3)
    at App
`

2023-09-29 15:06 UTC, DivergentEuropeans approved these changes
run-time error has been fixed, thank you 👍

2023-09-29 15:26 UTC, merged