Add Text Modification Operations to Dev Mode + Production Mode Context Menus
zowe/zen pull request #47
Opened 2023-09-25 19:50 UTC by timgerstel

This pull request implements the following feature:

- Introduce cut, copy, paste, undo, redo, and select all to Zen's context menu for both dev mode and production mode

2023-09-27 15:34 UTC, DivergentEuropeans requested changes
A pair of small things

2023-09-27 15:34 UTC, DivergentEuropeans commented on src/main/menu.ts
> +    this.mainWindow.webContents.on('context-menu', (_, props) => {
You're adding event listeners to `this.mainWindow.webContents`, but you're not removing them. I'm not very familiar with Electron's lifecycle, so it may do this already, but to be safe, it's better to add later on in the code:
`this.mainWindow.webContents.removeListener('context-menu', handleContextMenu);`

2023-09-27 15:34 UTC, DivergentEuropeans commented on src/main/menu.ts
> +    const selectAllAndCopyMenu = Menu.buildFromTemplate([
`selectAllAndCopyMenu` isn't being used is it? Did you intend to leave it - maybe a comment and a TODO for a later time?

2023-09-27 16:42 UTC, timgerstel commented on src/main/menu.ts
> +    this.mainWindow.webContents.on('context-menu', (_, props) => {
I think it gets cleaned up when the app closes, there is no context when the app is running where you wouldnt want this event listener

2023-09-27 16:42 UTC, timgerstel commented on src/main/menu.ts
> +    const selectAllAndCopyMenu = Menu.buildFromTemplate([
I had this in logic that i removed, ill remove the unused code good catch

2023-09-27 16:43 UTC, timgerstel commented on src/main/menu.ts
> +    this.mainWindow.webContents.on('context-menu', (_, props) => {
The electron boilerplate code for the dev environment doesnt even remove it

2023-09-28 00:28 UTC, DivergentEuropeans approved these changes
Nice, looks good

2023-09-28 00:29 UTC, DivergentEuropeans commented
Code makes sense now. I'll test in a day or two & we can merge

2023-10-02 20:59 UTC, 1000TurquoisePogs commented
works on mac but not linux, filing bug.

2023-10-02 20:59 UTC, merged