[WIP] DO NOT MERGE - Enhancement/certificate stage
zowe/zen pull request #79
Opened 2023-10-28 08:31 UTC by timgerstel

## Proposed changes

This PR addresses Issue: [*Link to Github issue within https://github.com/zowe/zen/issues* if any]

This PR depends upon the following PRs:

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Change in a documentation
- [ ] Refactor the code 
- [ ] Chore, repository cleanup, updates the dependencies.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## PR Checklist
Please delete options that are not relevant.
- [ ] If the changes in this PR are meant for the next release / mainline, this PR targets a "staging" branch.
- [ ] My code follows the style guidelines of this project (see: [Contributing guideline](https://github.com/zowe/zen/blob/v2.x/staging/CONTRIBUTING.md))
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes
- [ ] video or image is included if visual changes are made

- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works, or describe a test method below

## Testing

## Further comments

2023-10-30 10:33 UTC, 1000TurquoisePogs requested changes

2023-10-30 10:33 UTC, 1000TurquoisePogs commented on src/actions/InstallationHandler.ts
> +    const fs = require('fs');
fs is already imported at the top of the file though

2023-10-30 10:33 UTC, 1000TurquoisePogs commented on src/actions/InstallationHandler.ts
> +    const script = `cd ${installDir}/runtime/bin;\n./zwe init certificate -c ${installDir}/zowe.yaml`;
zwe init has many optional arguments. how can we let the user choose?

https://docs.zowe.org/stable/appendix/zwe_server_command_reference/zwe/init/zwe-init-certificate

`--update-config` is a good arg (probably we should default to it!) but it requires us to pull back the yaml when done, and consume it to get the changes.

`--allow-overwrite` also seems like a good arg, because without it you could just fail if the operation were done twice for 2 different installs.

`--security-dry-run` and similar dry-run stuff will be needed in a future ticket, so that we can show a preview before we do a thing.

2023-10-30 10:33 UTC, 1000TurquoisePogs commented on src/renderer/components/stages/Certificates.tsx
> +  const verifyCertsSchema = schema ? {"type": "object", "properties": {"verifyCertificates": schema.properties.zowe.properties.verifyCertificates}} : "";
what does this mean? why would our schema be empty?

2023-10-30 10:33 UTC, 1000TurquoisePogs commented on src/renderer/components/stages/Planning.tsx
> +        if (parseInt(details.spaceAvailableMb, 10) < 20) {
for testing purposes, dont commit.
can we have a little toggle somewhere so we dont keep doing this manually?

2023-10-30 13:11 UTC, timgerstel commented on src/renderer/components/stages/Planning.tsx
> +        if (parseInt(details.spaceAvailableMb, 10) < 20) {
Reverted

2023-10-30 13:14 UTC, timgerstel commented on src/actions/InstallationHandler.ts
> +    const fs = require('fs');
Removed

2023-10-30 13:16 UTC, timgerstel commented on src/renderer/components/stages/Certificates.tsx
> +  const verifyCertsSchema = schema ? {"type": "object", "properties": {"verifyCertificates": schema.properties.zowe.properties.verifyCertificates}} : "";
I did this because this is how @sakshibobade21 implemented it after implementing JsonForms:

https://github.com/zowe/zen/blob/v2.x/staging/src/renderer/components/stages/Security.tsx#L26
https://github.com/zowe/zen/blob/v2.x/staging/src/renderer/components/stages/installation/Installation.tsx#L33

Figured maybe she knew something we didn't

2023-10-30 13:17 UTC, timgerstel commented on src/actions/InstallationHandler.ts
> +    const script = `cd ${installDir}/runtime/bin;\n./zwe init certificate -c ${installDir}/zowe.yaml`;
Agree but I think this is out of scope for the ticket

2023-11-02 12:42 UTC, DivergentEuropeans requested changes

2023-11-02 12:42 UTC, DivergentEuropeans commented on src/actions/InstallationHandler.ts
> +      return ProgressStore.set('certificate.uploadYaml', false);;
double semi-colon

2023-11-02 12:42 UTC, DivergentEuropeans commented on src/renderer/components/stages/Certificates.tsx
> +  const verifyCertsConfig: any = (getZoweConfig() as any).zowe.verifyCertificates;
This gives me a run-time error at certificates step

`[14660:1102/075437.976:INFO:CONSOLE(46)]` "Uncaught TypeError: Cannot read properties of undefined (reading 'zowe')", source: webpack-internal:///./src/renderer/components/stages/Certificates.tsx (46)
[14660:1102/075437.987:INFO:CONSOLE(46)] "Uncaught TypeError: Cannot read properties of undefined (reading 'zowe')", source: webpack-internal:///./src/renderer/components/stages/Certificates.tsx (46)
[14660:1102/075437.993:INFO:CONSOLE(18687)] "The above error occurred in the <Certificates> component:

    at Certificates (webpack-internal:///./src/renderer/components/stages/Certificates.tsx:30:49)
    at div
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:57:66)
    at Box (webpack-internal:///./node_modules/@mui/system/esm/createBox.js:34:72)
    at HorizontalLinearStepper (webpack-internal:///./src/renderer/components/common/Stepper.tsx:49:13)
    at div
    at Wizard (webpack-internal:///./src/renderer/components/configuration-wizard/Wizard.tsx:37:133)
    at RenderedRoute (webpack-internal:///./node_modules/react-router/dist/index.js:715:5)
    at Outlet (webpack-internal:///./node_modules/react-router/dist/index.js:1118:26)
    at Header (webpack-internal:///./src/renderer/components/Header.tsx:47:60)
    at RenderedRoute (webpack-internal:///./node_modules/react-router/dist/index.js:715:5)
    at Routes (webpack-internal:///./node_modules/react-router/dist/index.js:1209:5)
    at Router (webpack-internal:///./node_modules/react-router/dist/index.js:1141:15)
    at HashRouter (webpack-internal:///./node_modules/react-router-dom/dist/index.js:372:5)
    at InnerThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:23:70)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js:45:5)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:42:5)
    at Provider (webpack-internal:///./node_modules/react-redux/es/components/Provider.js:16:3)
    at App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.", source: webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js (18687)
[14660:1102/075437.994:INFO:CONSOLE(12056)] "Uncaught TypeError: Cannot read properties of undefined (reading 'zowe')", source: webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js (12056)
`

2023-11-02 12:42 UTC, DivergentEuropeans commented on src/renderer/components/stages/Certificates.tsx
> +  const verifyCertsConfig: any = (getZoweConfig() as any).zowe.verifyCertificates;
This is achieved by running through the steps naturally,
and at Step 6 it's run-time TS error. Whatever the cause of the error, it's safer to do something like:

`const verifyCertsConfig: any = (getZoweConfig()?.zowe)?.verifyCertificates;
`

Lmk if you need help replicating the run-time error!

2023-11-13 16:15 UTC, 1000TurquoisePogs commented on src/actions/InstallationHandler.ts
> +    const script = `cd ${installDir}/runtime/bin;\n./zwe init certificate -c ${installDir}/zowe.yaml`;
i'm sure you 
* want `--update-config` and `--allow-overwrite` as a default, unless you like failures and manual labor (bugs me that these arent defaults in zwe itself)
* want to make a function that takes these as arguments so that in another ticket, you can make a UI that varies the functions.

2024-01-22 13:44 UTC, DivergentEuropeans commented on src/services/ConfigService.ts
> +export const setTopLevelZConfig = (section: string, data: any) => {
Doesn't this now code duplicate with ?
`setConfiguration = (section: string, data: any, setZconfig?: TRUE) => {`

2024-01-23 00:33 UTC, timgerstel commented on src/services/ConfigService.ts
> +export const setTopLevelZConfig = (section: string, data: any) => {
This actually already exists on staging so that needs to be removed from this PR anyway:
https://github.com/zowe/zen/blob/v2.x/staging/src/services/ConfigService.ts#L64

You are correct that there was 100% a better way to implement the needed functionality from the original function, but this one updates any level of the yaml instead of just zowe.setup. I should have just made the original update any section of the yaml, then updated the existing references I suppose. This must have been a bad time saving hack i though was appropriate at the time. Should be refactored.

2024-03-08 00:41 UTC, merged