Add Stage to Run 'zwe init apfauth`
zowe/zen pull request #82
Opened 2023-11-06 16:31 UTC by timgerstel

## Proposed changes
This pull request adds the following feature:
- Add stage to submit 'zwe init apfauth' command using previously entered dataset config
- Fields on stage are read only simply to show user what is about to be submitted with the zwe command

This PR depends upon the following PRs:

## Type of change
Please delete options that are not relevant.
- [X] New feature (non-breaking change which adds functionality)

## PR Checklist
Please delete options that are not relevant.
- [ ] If the changes in this PR are meant for the next release / mainline, this PR targets a "staging" branch.
- [ ] My code follows the style guidelines of this project (see: [Contributing guideline](https://github.com/zowe/zen/blob/v2.x/staging/CONTRIBUTING.md))
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes
- [ ] video or image is included if visual changes are made

- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works, or describe a test method below

## Testing

## Further comments

2023-11-09 16:08 UTC, 1000TurquoisePogs commented on src/actions/InstallationHandler.ts
> +      const script = `cd ${installationArgs.installationDir}/runtime/bin;\n./zwe init apfauth -c ${installationArgs.installationDir}/zowe.yaml`;
flags... 
this command has `--skip-security-setup` and `--security-dry-run` as options.
i believe this would manifest in buttons such as "preview" and "skip" (well, skip doesnt even need that flag i guess, it just... skips the whole page?)

not that different from other pages: 
* we want to be able to preview before we act
* we want to be able to skip, so that flows involving multiple admins can be done (skip those someone else did)

lastly, how would one see the result.jobOutput of this command? Perhaps from the editor stuff @sakshibobade21 was working on?

Dont need to solve everything in this PR, but we need a game plan for when we are going to solve such things, and a ticket so we dont forget.

2023-11-15 19:48 UTC, DivergentEuropeans requested changes, later dismissed
I get a run-time error. Are you able to replicate going from step 1, download from internet option (v2.x/staging + feature/apf/AuthStage)? It happens at Step 5, run init apfauth button

![image](https://github.com/zowe/zen/assets/20528015/8b8cb40c-bfcf-44b1-9b72-512d1cf1f096)

`writing current yaml to disk
Error occurred in handler for 'init-apf': TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFile (node:fs:2160:5)
    at FTPInstallation.<anonymous> (C:\Users\lastrakou\Desktop\zlux5\zen\.webpack\main\index.js:23659:22)
    at Generator.next (<anonymous>)
    at C:\Users\lastrakou\Desktop\zlux5\zen\.webpack\main\index.js:23593:71
    at new Promise (<anonymous>)
    at __webpack_modules__../src/actions/InstallationHandler.ts.__awaiter (C:\Users\lastrakou\Desktop\zlux5\zen\.webpack\main\index.js:23589:12)
    at FTPInstallation.apfAuth (C:\Users\lastrakou\Desktop\zlux5\zen\.webpack\main\index.js:23656:16)
    at InstallActions.apfAuth (C:\Users\lastrakou\Desktop\zlux5\zen\.webpack\main\index.js:23543:30)
    at C:\Users\lastrakou\Desktop\zlux5\zen\.webpack\main\index.js:24089:42
    at Generator.next (<anonymous>) {
  code: 'ERR_INVALID_ARG_TYPE'
}
[18704:1115/144023.634:INFO:CONSOLE(105)] "zwe init apfauth failed", source: webpack-internal:///./src/renderer/components/stages/InitApfAuth.tsx (105)`


but one small thing, you should add a little padding. The highlighted part of it touches the element above it 
![image](https://github.com/zowe/zen/assets/20528015/bcc8e9fd-7ccc-4b2d-93ed-698354a907bc)

and here
![image](https://github.com/zowe/zen/assets/20528015/769165f4-399f-4bc1-a591-d996c076b032)

2023-11-16 20:15 UTC, timgerstel commented
> I get a run-time error. Are you able to replicate going from step 1, download from internet option (v2.x/staging + feature/apf/AuthStage)? It happens at Step 5, run init apfauth button
> 
> ![image](https://user-images.githubusercontent.com/20528015/283230409-8b8cb40c-bfcf-44b1-9b72-512d1cf1f096.png)
> 
> `writing current yaml to disk Error occurred in handler for 'init-apf': TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined at Object.writeFile (node:fs:2160:5) at FTPInstallation.<anonymous> (C:\Users\lastrakou\Desktop\zlux5\zen\.webpack\main\index.js:23659:22) at Generator.next (<anonymous>) at C:\Users\lastrakou\Desktop\zlux5\zen\.webpack\main\index.js:23593:71 at new Promise (<anonymous>) at __webpack_modules__../src/actions/InstallationHandler.ts.__awaiter (C:\Users\lastrakou\Desktop\zlux5\zen\.webpack\main\index.js:23589:12) at FTPInstallation.apfAuth (C:\Users\lastrakou\Desktop\zlux5\zen\.webpack\main\index.js:23656:16) at InstallActions.apfAuth (C:\Users\lastrakou\Desktop\zlux5\zen\.webpack\main\index.js:23543:30) at C:\Users\lastrakou\Desktop\zlux5\zen\.webpack\main\index.js:24089:42 at Generator.next (<anonymous>) { code: 'ERR_INVALID_ARG_TYPE' } [18704:1115/144023.634:INFO:CONSOLE(105)] "zwe init apfauth failed", source: webpack-internal:///./src/renderer/components/stages/InitApfAuth.tsx (105)`
> 
> but one small thing, you should add a little padding. The highlighted part of it touches the element above it ![image](https://user-images.githubusercontent.com/20528015/283229006-bcc8e9fd-7ccc-4b2d-93ed-698354a907bc.png)
> 
> and here ![image](https://user-images.githubusercontent.com/20528015/283229343-769165f4-399f-4bc1-a591-d996c076b032.png)

I was unable to reproduce this:
![image](https://github.com/zowe/zen/assets/7998484/f177e6aa-787e-445d-8bd8-966e23411615)

2023-11-17 14:56 UTC, timgerstel commented
Update: I am still unable to reproduce the runtime error you got and I am able to see the correct job output after pressing "Run init apfauth" (see jira ticket for jcl)

2023-11-28 13:23 UTC, 1000TurquoisePogs reviewed
This works for me, aside from the other topics I brought up.

2024-01-09 23:38 UTC, struga0258 approved these changes

2024-01-10 00:02 UTC, merged