Enhance Installation Stage to Run 'zwe init mvs'
zowe/zen pull request #83
Opened 2023-11-09 05:05 UTC by timgerstel

## Proposed changes

This PR addresses Issue: [*Link to Github issue within https://github.com/zowe/zen/issues* if any]

This PR depends upon the following PRs:

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Change in a documentation
- [ ] Refactor the code 
- [ ] Chore, repository cleanup, updates the dependencies.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## PR Checklist
Please delete options that are not relevant.
- [ ] If the changes in this PR are meant for the next release / mainline, this PR targets a "staging" branch.
- [ ] My code follows the style guidelines of this project (see: [Contributing guideline](https://github.com/zowe/zen/blob/v2.x/staging/CONTRIBUTING.md))
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes
- [ ] video or image is included if visual changes are made

- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works, or describe a test method below

## Testing

## Further comments

2023-11-09 16:27 UTC, 1000TurquoisePogs commented on src/actions/InstallationHandler.ts
> +      const initMvs = await this.initMVS(connectionArgs, installationArgs.installationDir);
it looks to me like init mvs is run regardless of the status of install.

i think this file needs to be reorged a little bit to have a step only continue if the previous step succeeded.

because if you didnt upload, you cant unpax. if you didnt unpax, you cant install. if you didnt install, you cant init.

2023-11-13 16:18 UTC, 1000TurquoisePogs requested changes

2023-11-13 16:18 UTC, 1000TurquoisePogs commented on src/actions/InstallationHandler.ts
> +        initMvs = {status: true}
if installMvs = false, initMvs = true?
unconditionally?
i can't think of why this wouldnt be false.

2023-11-15 11:17 UTC, 1000TurquoisePogs commented on src/actions/InstallationHandler.ts
>        return {status: false, details: error.message};
This code does not properly present errors to users.

We have a try { } catch { } here, but not all failures go to the catch { } block.

If init mvs fails, there is no exception but the return would say `{status: false, details: ''}`.
There would be no way to differentiate that from a `zwe install` or `extract` step failure.

You should set `details` to what actually failed.
In fact, `initMVS()` is returning a details, so it could be formatted.

2023-11-16 18:29 UTC, timgerstel commented on src/actions/InstallationHandler.ts
>        return {status: false, details: error.message};
This return statement existed prior to this PR, I'd be happy to fix it but I think it should be a separate ticket to enhance the error detailing of this stage @1000TurquoisePogs

2023-11-27 21:23 UTC, DivergentEuropeans commented on src/actions/InstallationHandler.ts
>        return {status: false, details: error.message};
@timgerstel @1000TurquoisePogs don't forget, if there are new errors in Zen the user needs to see, use this:
https://github.com/zowe/zen/pull/45/files#diff-6d106a102cd6a61731f4cb784b463952dd7e6c02a2f1ba3df3e4602e9a4e7e45R222

2023-11-28 12:23 UTC, 1000TurquoisePogs approved these changes
It is an improvement so I will merge it but there still are situations that need to be caught:

<img width="1163" alt="image" src="https://github.com/zowe/zen/assets/30730276/aa3f8370-28cd-4a08-9f44-fee7fe3cc780">

If you run it twice, because "--allow-overwrite" is not used, technically `init` does nothing the second time.
It prints out warnings and then says success.
Those warnings should be propagated to the UI, which can be done in a follow-up PR.

2023-11-28 12:23 UTC, merged